// Owner-managed local account administration.
const bootstrapApi=LibreDisplayRuntime.getModule('bootstrap');
const {serverPath}=bootstrapApi;
const {escHtml,resilientFetch}=LibreDisplayRuntime.getModule('shared');


async function loadLocalAccounts(){const host=document.getElementById('account-list'),status=document.getElementById('account-status');if(!host||bootstrapApi.SESSION_ROLE!=='owner')return;try{const r=await resilientFetch(serverPath('/api/users'),{cache:'no-store'}),d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||('HTTP '+r.status));const rows=Array.isArray(d.users)?d.users:[];host.innerHTML=rows.length?rows.map(u=>`<div class="account-row"><b>${escHtml(u.username)}</b><span>${escHtml(u.role)}</span><span class="account-endpoints">${escHtml(u.role==='owner'?'All displays':(u.endpoints||[]).join(', ')||'No displays')}</span><span><button class="btn-util" type="button" onclick="editLocalAccount('${escHtml(u.username)}','${escHtml(u.role)}','${escHtml((u.endpoints||[]).join(','))}')">Edit</button> <button class="btn-util" type="button" onclick="deleteLocalAccount('${escHtml(u.username)}')">Delete</button></span></div>`).join(''):'<div class="settings-note">No local accounts yet. The local display and pairing link remain Owner access.</div>';if(status)status.textContent='';}catch(e){if(status)status.textContent='Could not load accounts: '+(e.message||e);}}
function editLocalAccount(username,role,endpoints){const u=document.getElementById('account-username'),r=document.getElementById('account-role'),e=document.getElementById('account-endpoints'),p=document.getElementById('account-password');if(u)u.value=username;if(r)r.value=role;if(e)e.value=endpoints;if(p)p.value='';}
async function saveLocalAccount(action){const status=document.getElementById('account-status');try{const username=(document.getElementById('account-username')?.value||'').trim(),role=document.getElementById('account-role')?.value||'viewer',password=document.getElementById('account-password')?.value||'',endpoints=(document.getElementById('account-endpoints')?.value||'').split(',').map(x=>x.trim()).filter(Boolean);const body={action,username,role,endpoints};if(password)body.password=password;const r=await resilientFetch(serverPath('/api/users'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),cache:'no-store'}),d=await r.json().catch(()=>({}));if(!r.ok||!d.ok)throw new Error(d.error||('HTTP '+r.status));if(status)status.textContent=action==='create'?'Account created.':'Account updated. Existing sessions for that user are invalidated when the password changes.';document.getElementById('account-password').value='';await loadLocalAccounts();}catch(e){if(status)status.textContent='Could not save account: '+(e.message||e);}}
async function deleteLocalAccount(username){if(!confirm(`Delete local account “${username}”?`))return;const status=document.getElementById('account-status');try{const r=await resilientFetch(serverPath('/api/users'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'delete',username}),cache:'no-store'}),d=await r.json().catch(()=>({}));if(!r.ok||!d.ok)throw new Error(d.error||('HTTP '+r.status));if(status)status.textContent='Account deleted and its active sessions invalidated.';await loadLocalAccounts();}catch(e){if(status)status.textContent='Could not delete account: '+(e.message||e);}}


// Preserve compatibility with existing inline event wiring while callers migrate to module APIs.
LibreDisplayRuntime.exposeModule("settings", {loadLocalAccounts,editLocalAccount,saveLocalAccount,deleteLocalAccount}, {}, {globalFunctions:['loadLocalAccounts','editLocalAccount','saveLocalAccount','deleteLocalAccount']});
