// Background media helpers for still images, HTML5 video, and raw Motion JPEG streams.
const {serverPath}=LibreDisplayRuntime.getModule('bootstrap');
const VIDEO_EXTENSIONS=new Set(['.mp4','.webm','.ogv','.m4v','.mov']);
const MJPEG_EXTENSIONS=new Set(['.mjpg','.mjpeg','.mpjpg']);
const MOTION_IMAGE_EXTENSIONS=new Set(['.gif']);
function backgroundMediaPath(value){const raw=String(value||'');try{const u=new URL(raw,location.href),p=u.searchParams.get('path');return decodeURIComponent(p||u.pathname||raw).toLowerCase();}catch(_e){return raw.toLowerCase();}}
function backgroundMediaKind(value){const raw=String(value||'');if(raw.startsWith('/media-mjpeg?'))return 'mjpeg';const path=backgroundMediaPath(raw),dot=path.lastIndexOf('.'),ext=dot>=0?path.slice(dot):'';if(MJPEG_EXTENSIONS.has(ext))return 'mjpeg';if(VIDEO_EXTENSIONS.has(ext))return 'video';return 'image';}
function backgroundMediaIsMotion(value){const path=backgroundMediaPath(value),dot=path.lastIndexOf('.'),ext=dot>=0?path.slice(dot):'';return backgroundMediaKind(value)!=='image'||MOTION_IMAGE_EXTENSIONS.has(ext);}
function backgroundMediaAssetUrl(value){const raw=String(value||'');return raw.startsWith('/media?')||raw.startsWith('/media-mjpeg?')?serverPath(raw):serverPath('/proxy?url='+encodeURIComponent(raw));}
function backgroundLayerMedia(layer,kind=null){if(!layer)return null;const resolved=kind||layer.dataset.mediaKind||'image';return resolved==='video'?layer.querySelector('video'):layer.querySelector('img');}
function backgroundMediaHasVisual(layer){if(!layer)return false;const kind=layer.dataset.mediaKind||'image',el=backgroundLayerMedia(layer,kind);return kind==='video'?!!(el&&el.readyState>=2&&el.videoWidth>0):!!(el&&el.complete&&el.naturalWidth>0);}
function resetBackgroundLayerMedia(layer){if(!layer)return;const img=layer.querySelector('img'),video=layer.querySelector('video');if(video){try{video.pause();}catch(_e){}video.removeAttribute('src');video.load?.();video.style.display='none';}if(img){img.removeAttribute('src');img.style.display='none';}layer.dataset.mediaKind='';layer.dataset.remoteUrl='';}
async function activateBackgroundLayerMedia(layer){if(!layer)return;const kind=layer.dataset.mediaKind||'image',img=layer.querySelector('img'),video=layer.querySelector('video');if(img)img.style.display=kind==='video'?'none':'block';if(video){video.style.display=kind==='video'?'block':'none';if(kind==='video'&&!document.documentElement.classList.contains('ld-reduce-motion')){try{await video.play();}catch(_e){}}}}
function deactivateBackgroundLayerMedia(layer,clear=false){if(!layer)return;const video=layer.querySelector('video');if(video)try{video.pause();}catch(_e){}if(clear)resetBackgroundLayerMedia(layer);}
function loadBackgroundMedia(layer,remoteUrl,priority='low'){
  if(!layer||!remoteUrl)return Promise.resolve(false);const kind=backgroundMediaKind(remoteUrl),assetUrl=backgroundMediaAssetUrl(remoteUrl),img=layer.querySelector('img'),video=layer.querySelector('video');if(!img||!video)return Promise.resolve(false);
  if(layer.dataset.remoteUrl===remoteUrl&&layer.dataset.mediaKind===kind&&backgroundMediaHasVisual(layer))return Promise.resolve(true);
  deactivateBackgroundLayerMedia(layer,false);if(kind==='video')img.removeAttribute('src');else{video.removeAttribute('src');video.load?.();}
  layer.dataset.remoteUrl=remoteUrl;layer.dataset.mediaKind=kind;
  if(kind==='video')return new Promise(resolve=>{let settled=false;const done=ok=>{if(settled)return;settled=true;video.onloadeddata=video.onerror=null;resolve(!!ok&&video.readyState>=2&&video.videoWidth>0);};video.style.display='block';img.style.display='none';video.muted=true;video.loop=true;video.playsInline=true;video.autoplay=false;video.preload='auto';video.onloadeddata=()=>done(true);video.onerror=()=>done(false);video.src=assetUrl;video.load();if(video.readyState>=2)setTimeout(()=>done(true),0);});
  return new Promise(resolve=>{let settled=false;const done=async ok=>{if(settled)return;settled=true;img.onload=img.onerror=null;if(ok&&kind==='image'&&typeof img.decode==='function'){try{await img.decode();}catch(_e){}}resolve(!!ok&&img.naturalWidth>0);};video.style.display='none';img.style.display='block';try{img.fetchPriority=priority;}catch(_e){}img.onload=()=>done(true);img.onerror=()=>done(false);img.src=assetUrl;if(img.complete)setTimeout(()=>done(img.naturalWidth>0),0);});
}
LibreDisplayRuntime.exposeModule('backgrounds',{VIDEO_EXTENSIONS,MJPEG_EXTENSIONS,MOTION_IMAGE_EXTENSIONS,backgroundMediaPath,backgroundMediaKind,backgroundMediaIsMotion,backgroundMediaAssetUrl,backgroundLayerMedia,backgroundMediaHasVisual,resetBackgroundLayerMedia,activateBackgroundLayerMedia,deactivateBackgroundLayerMedia,loadBackgroundMedia},{},{globalFunctions:[],globalStates:[]});
