import importlib.util
import re
import subprocess
import tempfile
import unittest
import zipfile
from pathlib import Path
from frontend_source import frontend_source

ROOT = Path(__file__).resolve().parents[1]


class ReleaseContractTests(unittest.TestCase):
    def test_public_release_identity_is_consistent(self):
        version = (ROOT / "VERSION").read_text(encoding="utf-8").strip()
        readme = (ROOT / "README.md").read_text(encoding="utf-8")
        cli = (ROOT / "scripts" / "libredisplay").read_text(encoding="utf-8")
        server = (ROOT / "app" / "dashboard_server.py").read_text(encoding="utf-8")
        self.assertRegex(version, r"^\d+\.\d+\.\d+$")
        self.assertIn(f"/archive/refs/tags/v{version}.zip", readme)
        self.assertIn("Gubna-Tech/LibreDisplay", readme)
        self.assertIn('REPOSITORY = "Gubna-Tech/LibreDisplay"', cli)
        self.assertIn("repos/Gubna-Tech/LibreDisplay/releases/latest", server)


    def test_public_tree_has_no_private_working_artifacts(self):
        forbidden_name_fragments = ("scratch", "checkpoint", "release-readiness-audit")
        for path in ROOT.rglob("*"):
            if not path.is_file():
                continue
            rel = path.relative_to(ROOT)
            lower_name = path.name.lower()
            self.assertFalse(any(fragment in lower_name for fragment in forbidden_name_fragments), f"private working note in release tree: {rel}")


    def test_public_tree_has_no_assistant_or_generated_working_notes(self):
        forbidden = (
            "generated by " + "chat" + "gpt", "chat" + "gpt" + " note", "open" + "ai" + " assistant", "assistant" + " note:",
            "a" + "i-" + "generated", "a" + "i " + "generated", "as an " + "a" + "i", "chain of " + "thought",
            "clau" + "de" + " generated", "co" + "pilot" + " generated", "gem" + "ini" + " generated",
        )
        text_suffixes = {".py", ".js", ".mjs", ".sh", ".html", ".css", ".md", ".txt", ".yml", ".yaml", ".json"}
        offenders = []
        for path in ROOT.rglob("*"):
            if not path.is_file() or path.suffix.lower() not in text_suffixes:
                continue
            text = path.read_text(encoding="utf-8", errors="ignore").lower()
            for phrase in forbidden:
                if phrase in text:
                    offenders.append(f"{path.relative_to(ROOT)}: {phrase}")
        self.assertEqual(offenders, [], "assistant/generated working notes leaked into release tree: " + ", ".join(offenders))

    def test_release_builder_matches_minimal_public_surface(self):
        source = (ROOT / "scripts" / "build-release.py").read_text(encoding="utf-8")
        for name in ("Dockerfile", "LICENSE", "README.md", "VERSION", "docker-compose.yml", "install.sh", "uninstall.sh", "update.sh"):
            self.assertIn(f'"{name}"', source)
        self.assertIn('TOP_DIRS = ("app", "assets", "plugins", "scripts", "tests")', source)
        self.assertIn('LibreDisplay-{version}', source)
        for forbidden in ("CHANGELOG.md", "CONTRIBUTING.md", "SECURITY.md", ".env.example", ".dockerignore", ".gitignore", ".github"):
            self.assertNotIn(f'"{forbidden}"', source)

    def test_release_builder_cannot_package_repository_or_runtime_extras(self):
        spec = importlib.util.spec_from_file_location("libredisplay_release_builder_test", ROOT / "scripts" / "build-release.py")
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)
        with tempfile.TemporaryDirectory(prefix="libredisplay-minimal-builder-") as td:
            workspace = Path(td) / "repo"
            workspace.mkdir()
            for name in module.TOP_FILES:
                (workspace / name).write_text("1.8.1\n" if name == "VERSION" else f"{name}\n", encoding="utf-8")
            for dirname in module.TOP_DIRS:
                (workspace / dirname).mkdir()
                (workspace / dirname / "project.txt").write_text("project\n", encoding="utf-8")
            for name in ("CHANGELOG.md", "CONTRIBUTING.md", "SECURITY.md", ".env.example", ".env", ".gitignore", ".dockerignore"):
                (workspace / name).write_text("do not ship\n", encoding="utf-8")
            (workspace / ".github").mkdir()
            (workspace / ".github" / "ci.yml").write_text("do not ship\n", encoding="utf-8")
            for dirname in ("data", "media", "backups", ".venv", ".libredisplay-update"):
                d = workspace / dirname
                d.mkdir()
                (d / "private.txt").write_text("secret\n", encoding="utf-8")
            (workspace / "private.ldbackup").write_text("secret\n", encoding="utf-8")
            output = Path(td) / "LibreDisplay-v1.8.1.zip"
            old_root = module.ROOT
            try:
                module.ROOT = workspace
                module.build(output)
            finally:
                module.ROOT = old_root
            with zipfile.ZipFile(output) as archive:
                names = set(archive.namelist())
            prefix = "LibreDisplay-1.8.1/"
            self.assertIn(prefix + "README.md", names)
            for dirname in module.TOP_DIRS:
                self.assertIn(prefix + dirname + "/project.txt", names)
            for forbidden in ("CHANGELOG.md", "CONTRIBUTING.md", "SECURITY.md", ".env.example", ".env", ".gitignore", ".dockerignore", ".github/ci.yml", "data/private.txt", "media/private.txt", "backups/private.txt", ".venv/private.txt", ".libredisplay-update/private.txt", "private.ldbackup"):
                self.assertNotIn(prefix + forbidden, names)

    def test_public_quickstart_matches_github_tag_zip_layout(self):
        readme = (ROOT / "README.md").read_text(encoding="utf-8")
        version = (ROOT / "VERSION").read_text(encoding="utf-8").strip()
        self.assertIn("unzip -q /tmp/LibreDisplay.zip -d ~/LibreDisplay-Setup", readme)
        self.assertIn(f"cd ~/LibreDisplay-Setup/LibreDisplay-{version}", readme)
        self.assertIn("## Remote access and privacy", readme)

    def test_readme_commands_are_copy_friendly_and_license_is_linked(self):
        readme = (ROOT / "README.md").read_text(encoding="utf-8")
        bash_blocks = re.findall(r"```bash\n(.*?)\n```", readme, re.S)
        self.assertTrue(bash_blocks)
        for block in bash_blocks:
            commands = [line for line in block.splitlines() if line.strip()]
            self.assertEqual(len(commands), 1)
        self.assertIn("[MIT License](LICENSE)", readme)
        self.assertTrue((ROOT / "LICENSE").is_file())

    def test_version_matches_dashboard_build(self):
        version = (ROOT / "VERSION").read_text(encoding="utf-8").strip()
        html = frontend_source(ROOT)
        match = re.search(r"const DASHBOARD_BUILD = '([^']+)'", html)
        self.assertIsNotNone(match)
        self.assertEqual(match.group(1), version)

    def test_v160_field_readiness_tool_is_part_of_project(self):
        self.assertTrue((ROOT / "scripts" / "field-readiness.py").is_file())
        self.assertIn("field-readiness.py", (ROOT / "install.sh").read_text(encoding="utf-8"))
        self.assertIn("field-readiness.py", (ROOT / "update.sh").read_text(encoding="utf-8"))

    def test_readme_and_native_update_helper_are_present(self):
        readme = (ROOT / "README.md").read_text(encoding="utf-8")
        self.assertIn("## Quick start — Raspberry Pi", readme)
        self.assertIn("libredisplay update", readme)
        update = ROOT / "update.sh"
        self.assertTrue(update.is_file())
        source = update.read_text(encoding="utf-8")
        self.assertIn('release-rollback.py', source)
        self.assertIn('snapshot --to-version "$NEW_VERSION"', source)
        self.assertIn('Your existing settings, display endpoints, media, and custom plugin folders were kept.', source)


    def test_v171_native_update_preserves_remote_access_state_and_data_directory(self):
        update = (ROOT / "update.sh").read_text(encoding="utf-8")
        self.assertEqual(update.count('DATA_DIR="$INSTALL_DIR/data"'), 1)
        self.assertNotIn('rm -rf "$DATA_DIR"', update)
        self.assertNotIn('libredisplay.env" <<', update)
        self.assertNotIn('remote_access.json', update)
        self.assertIn('Your existing settings, display endpoints, media, and custom plugin folders were kept.', update)

    def test_single_command_native_update_is_installed(self):
        readme = (ROOT / "README.md").read_text(encoding="utf-8")
        install = (ROOT / "install.sh").read_text(encoding="utf-8")
        update = (ROOT / "update.sh").read_text(encoding="utf-8")
        uninstall = (ROOT / "uninstall.sh").read_text(encoding="utf-8")
        cli = (ROOT / "scripts" / "libredisplay").read_text(encoding="utf-8")
        self.assertIn("libredisplay update", readme)
        self.assertIn('/usr/local/bin/libredisplay', install)
        self.assertIn('/usr/local/bin/libredisplay', update)
        self.assertIn('/usr/local/bin/libredisplay', uninstall)
        self.assertIn('API_URL = f"https://api.github.com/repos/{REPOSITORY}/releases/latest"', cli)
        self.assertIn('archive/refs/tags/v{latest}.zip', cli)
        self.assertNotIn('releases/download/', cli)
        self.assertNotIn('browser_download_url', cli)
        docker_release = (ROOT / "scripts" / "docker-release.py").read_text(encoding="utf-8")
        self.assertIn('archive/refs/tags/v{latest}.zip', docker_release)
        self.assertNotIn('releases/download/', docker_release)
        self.assertNotIn('browser_download_url', docker_release)
        self.assertIn('release_root = release_dir', cli)
        self.assertIn('safe_extract', cli)

    def test_v158_remote_updater_mode_stripping_cannot_block_frontend_verifier(self):
        update = (ROOT / "update.sh").read_text(encoding="utf-8")
        self.assertIn('[ -f "$SRC_DIR/scripts/verify-frontend.py" ]', update)
        self.assertNotIn('[ -x "$SRC_DIR/scripts/verify-frontend.py" ]', update)
        self.assertIn('python3 "$SRC_DIR/scripts/verify-frontend.py" "$SRC_DIR"', update)

    def test_v111_update_handles_chromium_runtime_links_before_legacy_backup(self):
        update = (ROOT / "update.sh").read_text(encoding="utf-8")
        backup = (ROOT / "scripts" / "server-backup.py").read_text(encoding="utf-8")
        self.assertIn('pkill -f -- "--user-data-dir=$DATA_DIR/chromium"', update)
        self.assertIn('for name in SingletonCookie SingletonLock SingletonSocket', update)
        self.assertLess(update.index("Stopping LibreDisplay and Chromium"), update.index("Creating a safety backup"))
        self.assertIn('CHROMIUM_RUNTIME_LINKS = {"SingletonCookie", "SingletonLock", "SingletonSocket"}', backup)
        self.assertIn('skip_symlink_rel=chromium_runtime_links', backup)

    def test_native_install_and_update_use_project_files_only(self):
        install = (ROOT / "install.sh").read_text(encoding="utf-8")
        update = (ROOT / "update.sh").read_text(encoding="utf-8")
        for source in (install, update):
            for forbidden in ("CHANGELOG.md", "CONTRIBUTING.md", "SECURITY.md", ".env.example", ".dockerignore", ".gitignore"):
                self.assertNotIn(forbidden, source)
        self.assertIn('is_incomplete_first_install', install)
        self.assertIn("Removing an incomplete previous LibreDisplay installation", install)

    def test_docker_image_carries_release_version(self):
        dockerfile = (ROOT / "Dockerfile").read_text(encoding="utf-8")
        self.assertIn("COPY --chown=libredisplay:libredisplay VERSION /VERSION", dockerfile)


    def test_v120_docker_update_path_preserves_state_and_health_checks(self):
        docker_setup = (ROOT / "scripts" / "docker-setup.sh").read_text(encoding="utf-8")
        docker_release = (ROOT / "scripts" / "docker-release.py").read_text(encoding="utf-8")
        html = frontend_source(ROOT)
        self.assertIn("./scripts/docker-setup.sh update", docker_setup)
        self.assertIn("Stopping LibreDisplay before the safety backup", docker_setup)
        self.assertLess(docker_setup.index("Stopping LibreDisplay before the safety backup"), docker_setup.index("Creating a safety backup before Docker source files change"))
        self.assertIn("wait_for_healthy", docker_setup)
        self.assertIn("rollback --workspace /workspace", docker_setup)
        for key in ("DASHBOARD_UID", "DASHBOARD_GID", "DASHBOARD_REMOTE_ENABLED", "DASHBOARD_REMOTE_NETWORKS", "DASHBOARD_ALLOWED_HOSTS", "DASHBOARD_CACHE_MAX_BYTES"):
            self.assertIn(f': "${{{key}:=', docker_setup)
        self.assertIn('MANAGED_DIRS = ("app", "scripts", "tests", "assets")', docker_release)
        self.assertIn('Docker state in data/, media/, .env, backups/, and custom plugin', docker_release)
        for forbidden in ("CHANGELOG.md", "CONTRIBUTING.md", "SECURITY.md", ".env.example", ".dockerignore", ".gitignore", ".github"):
            self.assertNotIn(f'"{forbidden}"', docker_release)
        self.assertIn("./scripts/docker-setup.sh update", html)

    def test_release_rollback_snapshots_project_files_only(self):
        rollback = (ROOT / "scripts" / "release-rollback.py").read_text(encoding="utf-8")
        for name in ("Dockerfile", "LICENSE", "README.md", "VERSION", "docker-compose.yml", "install.sh", "update.sh", "uninstall.sh"):
            self.assertIn(f'"{name}"', rollback)
        for forbidden in ("CHANGELOG.md", "CONTRIBUTING.md", "SECURITY.md", ".env.example", ".dockerignore", ".gitignore"):
            self.assertNotIn(forbidden, rollback)

    def test_native_update_swaps_project_top_files_atomically(self):
        update = (ROOT / "update.sh").read_text(encoding="utf-8")
        project_names = ("Dockerfile", "LICENSE", "README.md", "VERSION", "docker-compose.yml", "install.sh", "update.sh", "uninstall.sh")
        restore_block = update[update.index("restore_previous_release()") : update.index("cleanup_update_swap()")]
        replace_start = update.index("Replacing application files")
        replace_end = update.index("$DATA_DIR/.installed", replace_start)
        replace_block = update[replace_start:replace_end]
        self.assertIn('for old in "$OLD_DIR/files"/*', restore_block)
        for name in project_names:
            self.assertIn(name, replace_block)

    def test_native_partial_swap_rollback_restores_only_replaced_paths(self):
        update = (ROOT / "update.sh").read_text(encoding="utf-8")
        restore_block = update[update.index("restore_previous_release()") : update.index("cleanup_update_swap()")]
        self.assertIn('for old in "$OLD_DIR/plugins"/*', restore_block)
        self.assertIn('for marker in "$OLD_DIR/new-plugins"/*', restore_block)
        self.assertNotIn('for src in "$STAGE_DIR/plugins"/*', restore_block)
        with tempfile.TemporaryDirectory(prefix="libredisplay-partial-update-rollback-") as td:
            base = Path(td)
            install = base / "install"
            old = base / "old"
            data = install / "data"
            for path in (install / "app", install / "scripts", install / "assets", install / "plugins", data, old / "app", old / "plugins" / "bundled", old / "new-plugins", old / "files"):
                path.mkdir(parents=True, exist_ok=True)

            (install / "app" / "new.txt").write_text("new app", encoding="utf-8")
            (old / "app" / "old.txt").write_text("old app", encoding="utf-8")
            (install / "scripts" / "keep.txt").write_text("old scripts", encoding="utf-8")
            (install / "assets" / "keep.txt").write_text("old assets", encoding="utf-8")

            (install / "plugins" / "bundled").mkdir(exist_ok=True)
            (install / "plugins" / "bundled" / "plugin.py").write_text("new bundled", encoding="utf-8")
            (old / "plugins" / "bundled" / "plugin.py").write_text("old bundled", encoding="utf-8")
            (install / "plugins" / "untouched").mkdir()
            (install / "plugins" / "untouched" / "plugin.py").write_text("old untouched", encoding="utf-8")
            (install / "plugins" / "new-plugin").mkdir()
            (install / "plugins" / "new-plugin" / "plugin.py").write_text("new plugin", encoding="utf-8")
            (old / "new-plugins" / "new-plugin").write_text("", encoding="utf-8")
            (install / "plugins" / "custom-local").mkdir()
            (install / "plugins" / "custom-local" / "plugin.py").write_text("custom", encoding="utf-8")

            (install / "README.md").write_text("new readme", encoding="utf-8")
            (old / "files" / "README.md").write_text("old readme", encoding="utf-8")
            (install / "VERSION").write_text("1.8.1\n", encoding="utf-8")
            (old / "installed-version").write_text("1.6.1\n", encoding="utf-8")
            (data / ".installed").write_text("1.8.1\n", encoding="utf-8")

            result = subprocess.run(
                ["sh", "-c", restore_block + "\nrestore_previous_release\n"],
                env={"PATH": "/usr/bin:/bin", "INSTALL_DIR": str(install), "OLD_DIR": str(old), "DATA_DIR": str(data)},
                capture_output=True, text=True, check=False,
            )
            self.assertEqual(result.returncode, 0, result.stderr)
            self.assertEqual((install / "app" / "old.txt").read_text(), "old app")
            self.assertFalse((install / "app" / "new.txt").exists())
            self.assertEqual((install / "scripts" / "keep.txt").read_text(), "old scripts")
            self.assertEqual((install / "assets" / "keep.txt").read_text(), "old assets")
            self.assertEqual((install / "plugins" / "bundled" / "plugin.py").read_text(), "old bundled")
            self.assertEqual((install / "plugins" / "untouched" / "plugin.py").read_text(), "old untouched")
            self.assertFalse((install / "plugins" / "new-plugin").exists())
            self.assertEqual((install / "plugins" / "custom-local" / "plugin.py").read_text(), "custom")
            self.assertEqual((install / "README.md").read_text(), "old readme")
            self.assertEqual((install / "VERSION").read_text(), "1.8.1\n")
            self.assertEqual((data / ".installed").read_text(), "1.6.1\n")

    def test_release_tree_matches_v158_minimal_surface(self):
        expected = {"Dockerfile", "LICENSE", "README.md", "VERSION", "app", "assets", "docker-compose.yml", "install.sh", "plugins", "scripts", "tests", "uninstall.sh", "update.sh"}
        actual = {p.name for p in ROOT.iterdir() if p.name != "__pycache__"}
        self.assertEqual(actual, expected)
        readme = (ROOT / "README.md").read_text(encoding="utf-8")
        headings = [line for line in readme.splitlines() if line.startswith("#")]
        self.assertEqual(headings, [
            "# LibreDisplay",
            "## Quick start — Raspberry Pi",
            "## First setup",
            "## Using LibreDisplay",
            "## Updating LibreDisplay",
            "## Docker",
            "## Useful commands",
            "## Remote access and privacy",
            "## Open source",
        ])
        for forbidden in ("CHANGELOG.md", "CONTRIBUTING.md", "SECURITY.md", ".env.example", ".dockerignore", ".gitignore", ".github"):
            self.assertNotIn(forbidden, actual)

    def test_settings_exposes_calm_update_status(self):
        html = frontend_source(ROOT)
        server = (ROOT / "app" / "dashboard_server.py").read_text(encoding="utf-8")
        self.assertIn('id="health-software"', html)
        self.assertIn('id="settings-software-update"', html)
        self.assertIn('id="settings-update-badge"', html)
        self.assertIn('id="software-update-now"', html)
        self.assertIn('function checkSoftwareUpdate', html)
        self.assertIn('function startSoftwareUpdate', html)
        self.assertIn('/api/update-status', html)
        self.assertIn('/api/update-now', html)
        self.assertIn('/api/update-now', server)
        self.assertIn('/api/restore-points', html)
        self.assertIn('/api/restore-points', server)
        self.assertIn('create_restore_point', server)
        self.assertIn('portable-backup', html)
        self.assertIn('start_in_app_update', server)

    def test_native_installer_sets_up_narrow_update_helper(self):
        install = (ROOT / 'install.sh').read_text(encoding='utf-8')
        update = (ROOT / 'update.sh').read_text(encoding='utf-8')
        uninstall = (ROOT / 'uninstall.sh').read_text(encoding='utf-8')
        helper = (ROOT / 'scripts' / 'libredisplay-privileged').read_text(encoding='utf-8')
        self.assertIn('/usr/local/libexec/libredisplay-privileged', install)
        self.assertIn('NOPASSWD:', install)
        self.assertIn('probe, %s install-cli, %s reboot', install)
        self.assertIn('sudo -n "$PRIV_HELPER" probe', update)
        self.assertIn('sudo -n "$PRIV_HELPER" reboot', update)
        self.assertIn('/etc/sudoers.d/libredisplay-', uninstall)
        self.assertIn('case "${1:-}" in', helper)
        self.assertIn('install-cli)', helper)
        self.assertIn('reboot)', helper)

    def test_native_update_keeps_private_version_rollback_snapshots(self):
        update = (ROOT / "update.sh").read_text(encoding="utf-8")
        rollback = (ROOT / "scripts" / "release-rollback.py").read_text(encoding="utf-8")
        server = (ROOT / "app" / "dashboard_server.py").read_text(encoding="utf-8")
        html = frontend_source(ROOT)
        self.assertIn('Creating a safety backup and rollback snapshot', update)
        self.assertIn('record-update', update)
        self.assertIn('pre-update.ldbackup', rollback)
        self.assertIn('verify_snapshot', rollback)
        self.assertIn('/api/release-rollbacks', server)
        self.assertIn('/api/release-rollback', server)
        self.assertIn('id="settings-update-history"', html)
        self.assertIn('function startReleaseRollback', html)

    def test_server_user_agent_uses_release_version_dynamically(self):
        source = (ROOT / "app" / "dashboard_server.py").read_text(encoding="utf-8")
        self.assertIn('APP_VERSION = (PROJECT_ROOT / "VERSION").read_text', source)
        self.assertIn('f"LibreDisplay/{APP_VERSION}', source)
        self.assertNotRegex(source, r"LibreDisplay/\d+\.\d+\.\d+")

    def test_unversioned_json_raw_flag_is_supported(self):
        html = frontend_source(ROOT)
        self.assertIn("config.visualization=config.raw===true?'raw':'value'", html)

    def test_previous_layout_shape_is_supported(self):
        html = frontend_source(ROOT)
        self.assertIn("previousWeatherBlock", html)
        self.assertIn("previousForecastBlock", html)

    def test_task_renderer_forwards_provider_context(self):
        html = frontend_source(ROOT)
        self.assertIn("listId:task.listId||''", html)
        self.assertIn("t.listName||t.projectName", html)

    def test_block_editor_helpers_are_present(self):
        html = frontend_source(ROOT)
        for function_name in (
            "openBlockCatalog", "openBlockConfigEditor", "closeBlockConfig",
            "bf", "bsel", "bcheck", "integrationSettingsFieldsHtml",
        ):
            self.assertIn(f"function {function_name}", html)

    def test_integration_editor_accepts_normalized_setting_keys(self):
        html = frontend_source(ROOT)
        self.assertIn("function integrationSettingValue", html)
        self.assertIn("String(key||'').toLowerCase()", html)


    def test_calm_settings_information_architecture(self):
        html = frontend_source(ROOT)
        self.assertIn("const SETTINGS_TABS=['overview','weather','calendars','backgrounds','look','layout','family','integrations','system']", html)
        for section in ('settings-integrations', 'settings-accessibility'):
            self.assertIn(f'id="{section}"', html)
        self.assertIn('data-tab="family"', html)
        self.assertIn("integration-directory-search", html)
        self.assertIn("settings-mode-essential", html)

    def test_accessibility_and_layout_history_controls(self):
        html = frontend_source(ROOT)
        for marker in ("cfg._schemaVersion=2", "function applyAccessibilityPreferences", "Intl.DateTimeFormat", "function undoLayoutEditor", "function redoLayoutEditor"):
            self.assertIn(marker, html)

    def test_v110_calendar_background_and_element_size_fixes(self):
        html = frontend_source(ROOT)
        self.assertIn("fetchCal(c,i,{preferFormUrl:true})", html)
        self.assertIn("function testSingleCalendarSource", html)
        self.assertIn("const GOOGLE_PHOTOS_MAX_ITEMS=1000", html)
        self.assertNotIn("pages<20", html)
        self.assertIn('id="settings-backgrounds"', html)
        self.assertNotIn('id="settings-calendar-options"', html)
        self.assertNotIn('id="settings-background-options"', html)
        self.assertIn('id="layout-toolbar-scale"', html)
        self.assertIn("layoutContentScale", html)
        self.assertIn("_contentScale", html)

    def test_v122_google_photos_pagination_is_csp_safe(self):
        html = frontend_source(ROOT)
        self.assertIn("function extractGoogleInitialPageToken", html)
        self.assertIn("let token=extractGoogleInitialPageToken(html)", html)
        self.assertIn("Google Photos provided another page", html)
        self.assertNotIn("Function('\"use strict\";return (", html)
        self.assertEqual(html.count("</script>"), 1)
        self.assertIn("text.indexOf(');</scr'+'ipt>'", html)

    def test_v181_weather_controls_and_fast_start_paths_are_present(self):
        html = frontend_source(ROOT)
        for marker in (
            'id="s-weather-effect-precipitation"', 'id="s-weather-effect-clouds"',
            'id="s-weather-effect-fog"', 'id="s-weather-effect-sun"',
            'id="s-weather-effect-wind"', 'resetWeatherAnimationSettings()',
            'resetDisplayCareSettings()', 'libredisplay-last-background-v1',
            'libredisplay_air_quality_v1_', 'finishSecondaryHydration',
        ):
            self.assertIn(marker, html)
        effects = (ROOT / 'app/js/weather/effects.js').read_text(encoding='utf-8')
        self.assertIn("weatherEffectPrecipitation", effects)
        self.assertIn("weatherEffectWind", effects)
        self.assertNotIn("constrained)return true", effects)

    def test_v181_update_supports_legacy_install_missing_assets(self):
        rollback = (ROOT / 'scripts/release-rollback.py').read_text(encoding='utf-8')
        updater = (ROOT / 'update.sh').read_text(encoding='utf-8')
        self.assertIn('OPTIONAL_CODE_DIRS = ("assets",)', rollback)
        self.assertIn('if name in OPTIONAL_CODE_DIRS:', rollback)
        self.assertIn('new-code-dirs', updater)
        self.assertIn(': > "$OLD_DIR/new-code-dirs/$name"', updater)
        self.assertIn('verify-snapshot-install --snapshot-id "$SNAPSHOT_ID"', updater)
        self.assertIn('OPTIONAL_TOP_FILES', rollback)

    def test_v125_restores_v121_known_good_dashboard_hydration_path(self):
        html = frontend_source(ROOT)
        self.assertIn('<div id="setup" class="hidden" aria-hidden="true">', html)
        self.assertNotIn('function fetchWithTimeout', html)
        self.assertNotIn('fetchWithTimeout(', html)
        self.assertIn('id="settings-init-error"', html)
        self.assertIn('function showSettingsInitializationError', html)
        self.assertIn('switchSettingsTab(rememberedTab,false);', html)
        self.assertLess(html.index('switchSettingsTab(rememberedTab,false);'), html.index("document.getElementById('s-city').value=cfg.city||'';"))

        start = html.index('async function init(){')
        end = html.index('\n}\nconst dashboardInitPromise=init();', start)
        init = html[start:end]
        first_frame_order = [
            "await settings.loadSessionInfo();",
            "await config.loadCfg();",
            "appearance.applyUiCustomization(cfg);",
            "calendar.renderCalendar([]);",
            "settings.applySettings();",
            "remote.startLiveDisplayConnection();",
            "remote.startRemoteConfigPolling();",
        ]
        positions = [init.index(marker) for marker in first_frame_order]
        self.assertEqual(positions, sorted(positions))
        self.assertIn('const finishSecondaryHydration=async()=>', init)
        self.assertIn('await Promise.allSettled(jobs);', init)
        self.assertGreater(init.index("if(bootstrapApi.SESSION_ROLE==='owner')jobs.push(Promise.resolve(settings.loadLocalAccounts()));"), init.index('settings.applySettings();'))
        self.assertGreater(init.index('jobs.push(Promise.resolve(integrations.loadIntegrations())'), init.index('settings.applySettings();'))
        self.assertGreater(init.index('jobs.push(Promise.resolve(blocks.loadHousehold(false))'), init.index('settings.applySettings();'))
        self.assertIn('\nconst dashboardInitPromise=init();', html)
        self.assertNotIn('init().catch(', html)

        apply_start = html.index('function applySettings(){')
        apply_end = html.index('\n}\n\n\n// Browser cursor fallback.', apply_start)
        apply_body = html[apply_start:apply_end]
        for marker in (
            "performance.runExclusiveTask('weather-refresh',weather.fetchWeather);",
            "performance.runExclusiveTask('alert-refresh',weather.fetchWeatherAlerts);",
            "performance.runExclusiveTask('calendar-refresh',calendar.loadCalendars);",
        ):
            self.assertIn(marker, apply_body)
        self.assertIn("loadPhotos(cfg.photosUrl);", apply_body)

    def test_v121_layout_editor_customization_controls(self):
        html = frontend_source(ROOT)
        self.assertIn('id="settings-settings-button"', html)
        for marker in ('s-cog-position', 's-cog-opacity', 's-cog-size', 's-cog-label'):
            self.assertIn(marker, html)
        self.assertIn('id="layout-properties"', html)
        self.assertIn('layoutElementStyle', html)
        self.assertIn('function setSelectedLayoutStyle', html)
        self.assertIn('function placeSelectedLayoutBlock', html)
        self.assertIn('function applyBuiltInElementStyles', html)
        self.assertIn('existing._hAlign', html)
        for direction in ('nw', 'ne', 'sw', 'se'):
            self.assertIn(f'data-resize="{direction}"', html)


    def test_v126_layout_inspector_subsections_and_mobility(self):
        html = frontend_source(ROOT)
        for marker in (
            'id="layout-properties-drag-handle"',
            'id="layout-part-picker"',
            'id="layout-toolbar-scale-number"',
            'All event text',
            'layoutPartStyle',
            'const LAYOUT_PART_DEFS=',
            'const CUSTOM_LAYOUT_PART_DEFS=',
            'function setSelectedPartFineStyle',
            'function resetSelectedStyleScope',
            'function initLayoutInspectorDrag',
            'function buildCustomLayoutPartCss',
            'LAYOUT_INSPECTOR_POS_KEY',
            '_partStyles',
        ):
            self.assertIn(marker, html)
        self.assertIn("cal*ps('calendar','eventText')*ps('calendar','eventTitle')", html)
        self.assertIn("cal*ps('calendar','eventText')*ps('calendar','eventTime')", html)
        self.assertIn("cal*ps('calendar','dayNumber')", html)
        self.assertNotIn("cal*ps('calendar','eventText')*ps('calendar','dayNumber')", html)
        self.assertIn("document.addEventListener('pointermove'", html)
        self.assertIn("document.addEventListener('pointerup'", html)
        self.assertIn("max-height:calc(100vh - 88px)", html)
        self.assertEqual(html.count("</script>"), 1)

    def test_v127_alert_runtime_state_and_context_help(self):
        html = frontend_source(ROOT)
        start = html.index("function previewAlertMotionSpeed(value){")
        end = html.index("\n}\n\nfunction handleAlertMotionChange", start)
        preview = html[start:end]
        self.assertNotIn("syncAlertRuntimeStateFromForm", preview)
        self.assertIn("if(configApi.alertRuntimeState)configApi.alertRuntimeState.speed=speed;", preview)
        self.assertIn('id="context-help-popover"', html)
        self.assertIn('class="help-tip"', html)
        self.assertIn("function initContextHelp", html)
        self.assertIn("contextHelpPinned", html)
        self.assertIn("alertRuntimeState=null;\n      window.__uiPreviewCfg=null;\n      applySettings();", html)
        self.assertIn("const persistence=await saveCfg();", html)
        self.assertIn("if(options?.closeAfter!==false)closeSetup(false);\n  applySettings();", html)
        self.assertIn("await saveCfg();configApi.alertRuntimeState=null;window.__uiPreviewCfg=null;applySettings();openSetup(false)", html)
        self.assertIn("ensureCfgDefaults();cfg._savedAt=Date.now();", html)
        self.assertIn("persistCfgToServer(JSON.parse(JSON.stringify(cfg)));", html)
        self.assertIn("if(e.key==='Escape'&&activeContextHelpTip)", html)

    def test_v128_settings_preview_and_navigation_cleanup(self):
        html = frontend_source(ROOT)
        for marker in (
            'id="s-preview-button"',
            'id="settings-preview-return"',
            'function previewDashboardFromSettings',
            'function returnToSettingsPreview',
            'function requestCloseSetup',
            "settingsPreviewMode=true;",
            "syncAlertRuntimeStateFromForm();",
            "setTimeout(()=>restartAlertScroller(),100);",
            "SETTINGS_SEARCH_ALIASES",
            "settingsSectionSearchText",
            "calander",
            "Unsaved changes · preview only",
            "aria-expanded",
        ):
            self.assertIn(marker, html)
        self.assertNotIn("Click to collapse or expand this section", html)
        self.assertIn('onclick="requestCloseSetup()"', html)
        self.assertIn("if(e.key==='Escape'&&settingsApi().settingsPreviewMode)", html)
        self.assertIn("if(systemApi.settingsDirty&&!confirm('Discard unsaved changes?", html)
        self.assertIn("Preview test alerts full screen", html)

    def test_v129_alert_lifecycle_and_settings_readability(self):
        html = frontend_source(ROOT)
        for marker in (
            "function settingsOverlayOpen()",
            "if(settingsOverlayOpen()||LibreDisplayRuntime.getModule('settings').settingsPreviewMode)",
            "return savedAlertRuntimeState();",
            "function ensureAlertMotionRunning()",
            "function previewAlertTestFullScreen()",
            "Preview test alerts full screen",
            'id="s-settings-ui-size"',
            "settingsUiSize:'standard'",
            "setup.dataset.uiSize",
            "accessibility readable readability larger large text",
        ):
            self.assertIn(marker, html)
        self.assertIn('role="status" aria-live="polite"', html)
        self.assertIn("document.addEventListener('visibilitychange'", html)
        self.assertIn("window.addEventListener('resize',()=>setTimeout(ensureAlertMotionRunning,120));", html)

    def test_remote_alert_sync_and_public_readme_hygiene(self):
        html = frontend_source(ROOT)
        readme = (ROOT / "README.md").read_text(encoding="utf-8")
        assets = ROOT / "assets"
        self.assertEqual(sorted(p.name for p in assets.iterdir()), ['libredisplay-promo.png'])
        self.assertIn('<img src="assets/libredisplay-promo.png"', readme)
        self.assertTrue((assets / 'libredisplay-promo.png').is_file())
        self.assertIn("if(setupOpen&&(!bootstrapApi.REMOTE_SETTINGS_MODE||LibreDisplayRuntime.getModule('system').settingsDirty||LibreDisplayRuntime.getModule('settings').settingsPreviewMode))return;", html)
        self.assertIn("setTimeout(()=>{openSetup(false);setTimeout(ensureAlertMotionRunning,120);},0);", html)
        self.assertIn("startManagedInterval('remote-config-poll',pollServerConfig,bootstrapApi.REMOTE_SETTINGS_MODE?5000:30000", html)
        self.assertIn("liveEventSource.addEventListener('config',()=>LibreDisplayRuntime.getModule('performance').runExclusiveTask('remote-config-poll',pollServerConfig))", html)
        self.assertIn('"$SRC_DIR/assets"', (ROOT / 'install.sh').read_text(encoding='utf-8'))
        self.assertIn('"$SRC_DIR/assets"', (ROOT / 'update.sh').read_text(encoding='utf-8'))

    def test_v130_control_panel_settings_shell(self):
        html = frontend_source(ROOT)
        for marker in (
            'class="settings-workspace"',
            'class="settings-sidebar"',
            'class="settings-content"',
            'id="settings-page-title"',
            '<b>Home</b><small>Status, displays &amp; shortcuts</small>',
            '<b>Personalization</b><small>Themes, text &amp; accessibility</small>',
            "const SETTINGS_TAB_TITLES=",
            "function updateSettingsPageHeader(searchQuery='')",
            "title.textContent='Search results'",
            "grid-template-columns:252px minmax(0,1fr)",
        ):
            self.assertIn(marker, html)
        self.assertIn('@media(max-width:900px)', html)
        self.assertIn('aria-label="Settings navigation"', html)

    def test_v130_remote_arrange_uses_target_display_viewport(self):
        html = frontend_source(ROOT)
        server = (ROOT / "app" / "dashboard_server.py").read_text(encoding="utf-8")
        for marker in (
            'id="remote-layout-preview-shell"',
            'id="remote-layout-preview-frame"',
            "const LAYOUT_PREVIEW_MODE=PAGE_PARAMS.get('layoutPreview')==='1'",
            'function fetchRemoteLayoutTarget()',
            'function fitRemoteLayoutPreview()',
            'function displayViewportMetrics()',
            'layoutWidth,layoutHeight,viewportWidth,viewportHeight',
            "closeSetup(true);if(bootstrapApi.REMOTE_SETTINGS_MODE){setTimeout(openRemoteLayoutPreview,80);return;}",
            "notifyLayoutPreviewParent('saved')",
        ):
            self.assertIn(marker, html)
        self.assertIn('"viewportWidth": viewport_width', server)
        self.assertIn('"viewportHeight": viewport_height', server)
        self.assertIn('"screenWidth": screen_width', server)
        self.assertIn('"screenHeight": screen_height', server)

    def test_v131_display_fidelity_and_kiosk_hydration_recovery(self):
        html = frontend_source(ROOT)
        server = (ROOT / "app" / "dashboard_server.py").read_text(encoding="utf-8")
        start = (ROOT / "scripts" / "start.sh").read_text(encoding="utf-8")
        for marker in (
            "function displayViewportMetrics()",
            "layoutWidth,layoutHeight,viewportWidth,viewportHeight",
            "visualViewportWidth",
            "function requestFreshDisplayMetrics()",
            "action:'heartbeat'",
            "liveEventSource.addEventListener('heartbeat'",
            "function displayHydrationRecoveryNeeds()",
            "async function retryDisplayHydration(reason='scheduled')",
            "[5000,15000,35000,75000,150000]",
            "window.addEventListener('online'",
            "document.addEventListener('visibilitychange'",
        ):
            self.assertIn(marker, html)
        for marker in (
            '"layoutWidth": layout_width',
            '"layoutHeight": layout_height',
            '"visualViewportWidth": visual_viewport_width',
            '"visualViewportHeight": visual_viewport_height',
            'if action not in {"refresh", "reload", "heartbeat"}',
        ):
            self.assertIn(marker, server)
        self.assertIn('--disable-background-timer-throttling', start)
        self.assertIn('--disable-backgrounding-occluded-windows', start)
        self.assertIn('--disable-renderer-backgrounding', start)

    def test_v132_remote_layout_fresh_handshake_and_boot_polish(self):
        html = frontend_source(ROOT)
        server = (ROOT / "app" / "dashboard_server.py").read_text(encoding="utf-8")
        viewer = (ROOT / "scripts" / "viewer-setup.sh").read_text(encoding="utf-8")
        self.assertIn('<div id="setup" class="hidden" aria-hidden="true">', html)
        self.assertIn("function measureDashboardFontProbe(fontName)", html)
        self.assertIn("fontProbeWidth", html)
        self.assertIn("fontProbeHeight", html)
        self.assertIn("for(let attempt=0;attempt<18;attempt++)", html)
        self.assertIn("bestLayoutTargetDevice(rows,{freshSince:requestedAt-.15})", html)
        self.assertIn("Math.max(.1,Math.min(1,sw/tw,sh/th))", html)
        self.assertIn('"fontProbeWidth": font_probe_width', server)
        self.assertIn('"fontProbeHeight": font_probe_height', server)
        self.assertIn('fonts-liberation2 fonts-noto-core fonts-dejavu-core', viewer)

    def test_v133_remote_layout_preview_uses_same_origin_frame_route(self):
        html = frontend_source(ROOT)
        server_source = (ROOT / "app" / "dashboard_server.py").read_text(encoding="utf-8")
        self.assertIn("frame.src=`/layout-preview?endpoint=${encodeURIComponent(bootstrapApi.ACTIVE_ENDPOINT)}&layoutPreview=1", html)
        self.assertIn('if parsed.path == "/layout-preview":', server_source)
        self.assertIn('return urlparse(self.path).path == "/layout-preview"', server_source)
        self.assertIn('"SAMEORIGIN" if layout_preview else "DENY"', server_source)
        self.assertIn('frame_ancestors = "\'self\'" if layout_preview else "\'none\'"', server_source)
        self.assertNotIn("frame.src=`/dashboard.html?endpoint=${encodeURIComponent(bootstrapApi.ACTIVE_ENDPOINT)}&layoutPreview=1", html)

    def test_v134_remote_arrange_keeps_content_and_boxes_on_same_scale(self):
        html = frontend_source(ROOT)
        self.assertNotIn("LAYOUT_PREVIEW_TARGET_FONT_WIDTH", html)
        self.assertNotIn("LAYOUT_PREVIEW_FONT_METRIC_SCALE", html)
        self.assertNotIn("refreshLayoutPreviewFontCalibration", html)
        self.assertIn("const s=((Number(pct)||100)/100);", html)
        self.assertIn('id="remote-layout-element-picker"', html)
        self.assertIn("function selectRemoteLayoutElement(key)", html)
        self.assertIn("function syncRemoteEditorHitTargets(scale)", html)
        self.assertNotIn("wall font calibrated", html)
        self.assertNotIn("targetFontProbeWidth=", html)


    def test_v135_remote_arrange_separates_target_canvas_from_laptop_editor_chrome(self):
        html = frontend_source(ROOT)
        for marker in (
            "body.layout-preview-embedded #layout-toolbar",
            "body.layout-preview-embedded #layout-properties",
            "body.remote-layout-proxy #layout-toolbar",
            "body.remote-layout-proxy #layout-properties",
            "function activateRemoteLayoutProxy()",
            "function deactivateRemoteLayoutProxy()",
            "function handleRemoteLayoutProxyEvent(e)",
            "function syncRemoteLayoutProxyUi()",
            "remoteLayoutProxySyncTimer=setInterval(syncRemoteLayoutProxyUi,140)",
            "--ld-editor-handle-size",
        ):
            self.assertIn(marker, html)
        self.assertNotIn("--ld-editor-ui-inv-scale", html)
        self.assertNotIn("body.layout-preview-embedded #layout-properties{top:var(", html)
        self.assertNotIn("body.custom-layout .wx-details {\n  width:auto !important;", html)
        self.assertIn("body.custom-layout .wx-details {\n  width:auto;", html)

    def test_v140_arrange_workspace_uses_explicit_target_canvas_and_safe_close(self):
        html = frontend_source(ROOT)
        for marker in (
            "let layoutSessionViewport=null;",
            "function layoutViewportSize()",
            "function refreshLayoutSessionViewport()",
            "['layoutWidth','layoutHeight','layout viewport']",
            "if(!row||!['local','viewer'].includes(String(row.mode||'')))return null;",
            "if(rawW<480||rawH<270||rawW>7680||rawH>4320)return null;",
            "Math.max(.1,Math.min(1,sw/tw,sh/th))",
            "body.remote-layout-proxy #remote-layout-preview-stage{top:112px;right:350px}",
            "frame.onload=null;frame.removeAttribute('src');frame.src='about:blank';",
            "layoutApi().layoutInspectorDragState=null;layoutApi().layoutSessionViewport=null;",
            "const hadSession=layoutEditorActive||!!layoutApi().layoutEditorOriginal;",
        ):
            self.assertIn(marker, html)
        self.assertIn("session!==remoteLayoutPreviewSession||!shell.classList.contains('show')", html)
        self.assertNotIn("severeOverflow=visual", html)
        self.assertNotIn("Math.max(.1,Math.min(4,sw/tw,sh/th))", html)
        self.assertNotIn("using 1920×1080 fallback", html)
        self.assertIn("Arrange unavailable · the wall display has not reported a valid viewport yet", html)
        self.assertNotIn("legacyBuiltInCollisionCount", html)
        self.assertIn("--ld-layout-fit-current", html)
        clock_custom = html.split("body.custom-layout #clock-block {", 1)[1].split("}", 1)[0]
        self.assertNotIn("padding:0 !important", clock_custom)

    def test_v143_arrange_round_trip_and_editability_contract(self):
        html = frontend_source(ROOT)
        for marker in (
            "function validStoredLayoutRect(r)",
            "function cloneLayoutRect(r)",
            "function layoutRectForDisplay(key,r)",
            "function customBlockRectForDisplay(block,r=block?.rect)",
            "function normalizeCustomBlockDraftRects(blocks)",
            "layoutCustomBlocksDraft=normalizeCustomBlockDraftRects",
            "entries.sort((a,b)=>(Number(b.r.w)*Number(b.r.h))-(Number(a.r.w)*Number(a.r.h)))",
            "daily:{selector:'#wx-forecast',label:'Daily Forecast'",
            "hourly:{selector:'#wx-hourly-block',label:'Hourly Forecast'",
        ):
            self.assertIn(marker, html)
        self.assertNotIn("layoutEditorRecoveredLegacy", html)
        self.assertNotIn("legacyBuiltInCollisionCount", html)

    def test_v143_remote_arrange_reopen_waits_for_hydration_and_persistence(self):
        html = frontend_source(ROOT)
        for marker in (
            "const dashboardInitPromise=init();",
            "if(LAYOUT_PREVIEW_MODE)dashboardInitPromise.then(()=>autoStartLayoutPreviewWhenReady())",
            "return persistCfgToServer(JSON.parse(JSON.stringify(cfg)))",
            "async function saveLayoutEditor()",
            "const persisted=await saveCfg();",
            "if(LAYOUT_PREVIEW_MODE&&!persisted?.ok)",
            "async function handleEmbeddedLayoutEditorAction(action)",
            "await pollServerConfig();",
        ):
            self.assertIn(marker, html)
        self.assertNotIn("setTimeout(()=>notifyLayoutPreviewParent('saved'),160)", html)
        self.assertNotIn("if(LAYOUT_PREVIEW_MODE)autoStartLayoutPreviewWhenReady();", html)

    def test_v143_weather_details_arrange_grid_tracks_rendered_cells(self):
        html = frontend_source(ROOT)
        for marker in (
            "function syncWeatherDetailsArrangeGrid(el)",
            "const count=el.querySelectorAll(':scope > .wx-detail').length",
            "const cols=weatherDetailColumnCount(count)",
            "if(details)syncWeatherDetailsArrangeGrid(details);",
        ):
            self.assertIn(marker, html)

    def test_chart_controls_and_versioned_import(self):
        html = frontend_source(ROOT)
        for marker in ("bc-chart-area", "bc-chart-points", "bc-chart-grid", "function analyzeImportedSettings", "product:'LibreDisplay',format:2"):
            self.assertIn(marker, html)

    def test_native_renderers_and_accounts_ui_are_present(self):
        html = frontend_source(ROOT)
        for function_name in ("renderIntegrationPhotos", "renderIntegrationStatus", "renderIntegrationMap", "renderIntegrationMessages", "loadLocalAccounts"):
            self.assertIn(f"function {function_name}", html)
        self.assertIn('id="settings-users"', html)


if __name__ == "__main__":
    unittest.main()
