const performanceApi=LibreDisplayRuntime.getModule('performance');
let canvasState={canvas:null,ctx:null,host:null,raf:0,lastFrame:0,lastPaint:0,width:0,height:0,pixelWidth:0,pixelHeight:0,renderScale:1,sceneKey:'',particles:[],running:false,frames:0};

function canvasClamp(value,lo,hi,fallback=lo){value=Number(value);return Math.min(hi,Math.max(lo,Number.isFinite(value)?value:fallback));}
function canvasSeed(index,salt=0){const x=Math.sin((index+1)*12.9898+(salt+1)*78.233)*43758.5453;return x-Math.floor(x);}
function piCanvasSupported(source={}){const caps=performanceApi.frontendCapabilities();return !!(caps.piClass&&source.lightweightModeEnabled!==true&&!document.documentElement.classList.contains('ld-reduce-motion'));}
function piCanvasHostVisible(){const host=canvasState.host;if(!host?.isConnected||document.hidden)return false;const style=getComputedStyle(host);return style.display!=='none'&&style.visibility!=='hidden'&&Number(style.opacity||1)>.01;}
function ensurePiCanvas(host){if(canvasState.canvas?.isConnected&&canvasState.host===host)return canvasState.canvas;stopPiCanvasScene();const canvas=document.createElement('canvas');canvas.className='weather-fx-pi-canvas';canvas.setAttribute('aria-hidden','true');host.appendChild(canvas);canvasState={...canvasState,canvas,ctx:canvas.getContext('2d',{alpha:true,desynchronized:true}),host,running:true,lastFrame:0,lastPaint:0,frames:0,particles:[]};resizePiCanvas();return canvas;}
function piCanvasRenderScale(){const budget=performanceApi.visualPerformanceBudget(),tier=budget.resolutionTier||'standard',quality=Math.max(.42,Math.min(1,Number(budget.adaptiveQuality)||1));return Math.max(.30,Math.min(.78,(tier==='4k'?.36:tier==='highres'?.54:.72)*(.82+quality*.18)));}
function resizePiCanvas(){const canvas=canvasState.canvas,host=canvasState.host;if(!canvas||!host)return;const rect=host.getBoundingClientRect(),width=Math.max(1,Math.round(rect.width||innerWidth||1280)),height=Math.max(1,Math.round(rect.height||innerHeight||720)),scale=piCanvasRenderScale(),pixelWidth=Math.max(1,Math.round(width*scale)),pixelHeight=Math.max(1,Math.round(height*scale));if(width===canvasState.width&&height===canvasState.height&&pixelWidth===canvasState.pixelWidth&&pixelHeight===canvasState.pixelHeight)return;canvasState.width=width;canvasState.height=height;canvasState.pixelWidth=pixelWidth;canvasState.pixelHeight=pixelHeight;canvasState.renderScale=scale;canvas.width=pixelWidth;canvas.height=pixelHeight;canvas.style.width=`${width}px`;canvas.style.height=`${height}px`;canvasState.ctx?.setTransform(scale,0,0,scale,0,0);}
function particle(kind,index,total,wind,source){const w=canvasState.width||innerWidth||1280,h=canvasState.height||innerHeight||720,x=canvasSeed(index,1)*w,y=canvasSeed(index,2)*h,depth=.45+canvasSeed(index,3)*.55,windPx=(Number(wind?.direction)||0)*(Number(wind?.strength)||0)*28;let vx=windPx*(.22+depth*.34),vy=50,size=2,alpha=.7,spin=(canvasSeed(index,5)-.5)*1.8;if(kind==='rain'){vy=520+depth*380;vx+=windPx*1.6;size=8+depth*13;alpha=.35+depth*.48;}else if(kind==='snow'){vy=32+depth*54;vx+=windPx*.75;size=1.4+depth*2.4;alpha=.48+depth*.42;}else if(kind==='leaves'){vy=28+depth*40;vx+=windPx*.65;size=2.6+depth*3.8;alpha=.45+depth*.45;}else if(kind==='petals'){vy=22+depth*30;vx+=windPx*.42;size=2+depth*2.8;alpha=.50+depth*.38;}else if(kind==='crystals'){vy=24+depth*32;vx+=windPx*.28;size=1.8+depth*2.6;alpha=.38+depth*.42;}else if(kind==='fireflies'){vy=(canvasSeed(index,6)-.5)*8;vx=(canvasSeed(index,7)-.5)*13;size=1.2+depth*1.8;alpha=.42+depth*.44;}return {kind,x,y,vx,vy,size,alpha,spin,angle:canvasSeed(index,8)*Math.PI*2,phase:canvasSeed(index,9)*Math.PI*2,total,source};}
function distributeCanvasParticles(scene){const budget=performanceApi.visualPerformanceBudget(),max=Math.max(8,Number(budget.maxParticles)||24),primaryKind=scene.condition==='snow'?'snow':(['rain','storm'].includes(scene.condition)?'rain':''),primaryRequested=primaryKind?Math.max(0,Number(scene.count)||0):0,season=scene.seasonalCounts||{},secondaryKinds=['leaves','petals','crystals','fireflies'],requested=secondaryKinds.map(kind=>[kind,Math.max(0,Number(season[kind])||0)]),primaryCap=primaryRequested?Math.max(6,Math.round(max*.76)):0,rows=[];if(primaryRequested)rows.push([primaryKind,Math.min(primaryRequested,primaryCap)]);let left=max-rows.reduce((n,r)=>n+r[1],0),secondaryTotal=requested.reduce((n,r)=>n+r[1],0);for(const [kind,n] of requested){if(!n||left<=0)continue;const share=secondaryTotal?Math.max(1,Math.round(left*n/secondaryTotal)):0,amount=Math.min(n,share,left);rows.push([kind,amount]);left-=amount;}return rows;}
function buildCanvasParticles(scene){const rows=distributeCanvasParticles(scene),out=[];let offset=0;for(const [kind,count] of rows){for(let i=0;i<count;i++)out.push(particle(kind,offset+i,count,scene.wind,scene.source));offset+=count+37;}return out;}
function drawRain(ctx,p){ctx.globalAlpha=p.alpha;ctx.strokeStyle='rgba(205,229,245,.92)';ctx.lineWidth=Math.max(.6,p.size*.075);ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(p.x-p.vx*.012,p.y-p.size);ctx.stroke();}
function drawSnow(ctx,p){ctx.globalAlpha=p.alpha;ctx.fillStyle='#f5fbff';ctx.beginPath();ctx.arc(p.x,p.y,p.size,0,Math.PI*2);ctx.fill();}
function drawLeaf(ctx,p){ctx.globalAlpha=p.alpha;ctx.fillStyle=`hsl(${22+Math.round((p.phase/Math.PI)*13)} 58% 44%)`;ctx.save();ctx.translate(p.x,p.y);ctx.rotate(p.angle);ctx.beginPath();ctx.ellipse(0,0,p.size*1.35,p.size*.55,0,0,Math.PI*2);ctx.fill();ctx.restore();}
function drawPetal(ctx,p){ctx.globalAlpha=p.alpha;ctx.fillStyle='rgba(248,178,213,.95)';ctx.save();ctx.translate(p.x,p.y);ctx.rotate(p.angle);ctx.beginPath();ctx.ellipse(0,0,p.size,p.size*.56,.45,0,Math.PI*2);ctx.fill();ctx.restore();}
function drawCrystal(ctx,p){ctx.globalAlpha=p.alpha;ctx.strokeStyle='rgba(220,244,255,.88)';ctx.lineWidth=.8;ctx.beginPath();ctx.moveTo(p.x-p.size,p.y);ctx.lineTo(p.x+p.size,p.y);ctx.moveTo(p.x,p.y-p.size);ctx.lineTo(p.x,p.y+p.size);ctx.stroke();}
function drawFirefly(ctx,p,now){const pulse=.45+.55*Math.sin(now*.003+p.phase)**2;ctx.globalAlpha=p.alpha*pulse;ctx.fillStyle='rgba(255,235,111,.95)';ctx.beginPath();ctx.arc(p.x,p.y,p.size,0,Math.PI*2);ctx.fill();}
function resetParticle(p,w,h){if(p.y>h+30){p.y=-20;p.x=(p.x+canvasSeed(Math.round(p.x+p.size),11)*w*.35)%w;}if(p.x>w+40)p.x=-30;if(p.x<-40)p.x=w+30;}
function paintPiCanvas(now,dt){const ctx=canvasState.ctx,w=canvasState.width,h=canvasState.height;if(!ctx||!w||!h)return;ctx.save();ctx.setTransform(1,0,0,1,0,0);ctx.clearRect(0,0,canvasState.pixelWidth,canvasState.pixelHeight);ctx.restore();ctx.setTransform(canvasState.renderScale,0,0,canvasState.renderScale,0,0);for(const p of canvasState.particles){const wave=Math.sin(now*.0016+p.phase);p.x+=(p.vx+wave*(p.kind==='snow'||p.kind==='petals'?7:2))*dt;p.y+=p.vy*dt;p.angle+=p.spin*dt;if(p.kind==='fireflies'){p.x+=Math.cos(now*.001+p.phase)*6*dt;p.y+=Math.sin(now*.0014+p.phase)*5*dt;}resetParticle(p,w,h);if(p.kind==='rain')drawRain(ctx,p);else if(p.kind==='snow')drawSnow(ctx,p);else if(p.kind==='leaves')drawLeaf(ctx,p);else if(p.kind==='petals')drawPetal(ctx,p);else if(p.kind==='crystals')drawCrystal(ctx,p);else if(p.kind==='fireflies')drawFirefly(ctx,p,now);}ctx.globalAlpha=1;canvasState.lastPaint=Date.now();canvasState.frames++;}
function piCanvasLoop(now){if(!canvasState.running)return;canvasState.raf=requestAnimationFrame(piCanvasLoop);if(!piCanvasHostVisible())return;resizePiCanvas();const interval=performanceApi.animationPerformanceFrameMs?.()||16;if(canvasState.lastFrame&&now-canvasState.lastFrame<interval*.88)return;const dt=Math.min(.05,Math.max(.008,(now-(canvasState.lastFrame||now-interval))/1000));canvasState.lastFrame=now;paintPiCanvas(now,dt);}
function updatePiCanvasScene(host,scene){if(!piCanvasSupported(scene?.source||{})){stopPiCanvasScene();return false;}ensurePiCanvas(host);const key=JSON.stringify([scene.condition,scene.count,scene.season,scene.seasonalCounts,Math.round(Number(scene.wind?.strength||0)*10),Math.round(Number(scene.wind?.direction||0)*10),performanceApi.visualPerformanceBudget().maxParticles,Number(piCanvasRenderScale().toFixed(2))]);if(key!==canvasState.sceneKey){canvasState.sceneKey=key;canvasState.particles=buildCanvasParticles(scene);canvasState.lastFrame=0;}if(!canvasState.raf){canvasState.running=true;canvasState.raf=requestAnimationFrame(piCanvasLoop);}return true;}
function stopPiCanvasScene(){if(canvasState.raf)cancelAnimationFrame(canvasState.raf);canvasState.canvas?.remove();canvasState={canvas:null,ctx:null,host:null,raf:0,lastFrame:0,lastPaint:0,width:0,height:0,pixelWidth:0,pixelHeight:0,renderScale:1,sceneKey:'',particles:[],running:false,frames:0};}
function piCanvasHealth(){return {running:canvasState.running&&!!canvasState.canvas?.isConnected,lastPaint:canvasState.lastPaint,frames:canvasState.frames,particles:canvasState.particles.length,renderScale:Number(canvasState.renderScale.toFixed(2)),pixelWidth:canvasState.pixelWidth,pixelHeight:canvasState.pixelHeight,healthy:canvasState.running&&Date.now()-canvasState.lastPaint<6000};}
function piCanvasDomSelectors(){return ['.weather-fx-primary','.weather-fx-splash','.weather-fx-leaf','.weather-fx-petal','.weather-fx-crystal','.weather-fx-firefly'];}

globalThis.addEventListener?.('resize',()=>{if(canvasState.running)resizePiCanvas();},{passive:true});
globalThis.addEventListener?.('beforeunload',stopPiCanvasScene);
LibreDisplayRuntime.exposeModule('weatherCanvas',{piCanvasSupported,piCanvasRenderScale,updatePiCanvasScene,stopPiCanvasScene,piCanvasHealth,piCanvasDomSelectors},{},{globals:false});
