// NatureScape companion character and holiday-overlay runtime.
const DOG_BREEDS=new Set(['labrador','golden','german-shepherd','white-swiss-shepherd','great-pyrenees','nova-scotia-duck-tolling-retriever','border-collie','australian-shepherd','beagle','corgi','dachshund','french-bulldog','poodle','husky','shiba','boxer','great-dane','chihuahua']);
const LABRADOR_COATS=new Set(['black','yellow','fox-red','chocolate']);
const DOG_COLLARS=new Set(['none','red','blue','teal','green','purple','pink','orange','black','brown']);
const HOLIDAY_KEYS=['new-year','valentines','st-patrick','easter','memorial','juneteenth','independence','labor','halloween','day-of-dead','veterans','thanksgiving','hanukkah','christmas'];
const HOLIDAY_CONFIG={
  'new-year':'holidayOverlayNewYear','valentines':'holidayOverlayValentines','st-patrick':'holidayOverlayStPatrick','easter':'holidayOverlayEaster','memorial':'holidayOverlayMemorial','juneteenth':'holidayOverlayJuneteenth','independence':'holidayOverlayIndependence','labor':'holidayOverlayLabor','halloween':'holidayOverlayHalloween','day-of-dead':'holidayOverlayDayOfDead','veterans':'holidayOverlayVeterans','thanksgiving':'holidayOverlayThanksgiving','hanukkah':'holidayOverlayHanukkah','christmas':'holidayOverlayChristmas'
};
const HOLIDAY_LABELS={'new-year':"New Year's Day",valentines:"Valentine's Day",'st-patrick':"St. Patrick's Day",easter:'Easter',memorial:'Memorial Day',juneteenth:'Juneteenth',independence:'Independence Day',labor:'Labor Day',halloween:'Halloween','day-of-dead':'Day of the Dead',veterans:'Veterans Day',thanksgiving:'Thanksgiving',hanukkah:'Hanukkah',christmas:'Christmas'};
let dogRuntime={timer:0,node:null,serial:0,lastState:'rest'};
let holidayTestProfile='live';
let holidayRefresh=null;
function sceneryClamp(n,lo,hi,fallback=lo){n=Number(n);return Math.min(hi,Math.max(lo,Number.isFinite(n)?n:fallback));}
function rand(lo=0,hi=1){return lo+Math.random()*(hi-lo);}
function choice(rows){const total=rows.reduce((n,r)=>n+r[1],0);let x=Math.random()*total;for(const row of rows){x-=row[1];if(x<=0)return row[0];}return rows.at(-1)?.[0]||'rest';}
function stopDogRuntime(){if(dogRuntime.timer)clearTimeout(dogRuntime.timer);dogRuntime={timer:0,node:null,serial:dogRuntime.serial+1,lastState:'rest'};}
function dogReducedMotion(source){if(source?.weatherEffectRespectReducedMotion===false)return false;if(source?.motionPreference==='reduced')return true;return source?.motionPreference!=='full'&&!!window.matchMedia?.('(prefers-reduced-motion: reduce)')?.matches;}
function dogPerchTarget(node){const vw=window.innerWidth||1280,vh=window.innerHeight||720,candidates=[...document.querySelectorAll('#clock-block,#wx-left,#wx-right,.custom-block,#calendar-legend,#alert-zone')].filter(el=>{const r=el.getBoundingClientRect();const cs=getComputedStyle(el);return cs.display!=='none'&&cs.visibility!=='hidden'&&r.width>95&&r.height>24&&r.top>70&&r.top<vh-145&&r.right>40&&r.left<vw-40;});if(!candidates.length)return null;const r=candidates[Math.floor(Math.random()*candidates.length)].getBoundingClientRect();return {x:sceneryClamp(r.left+r.width*rand(.12,.72),8,vw-170,20),bottom:sceneryClamp(vh-r.top-3,22,vh-115,36),perch:true};}
function lowBirdTarget(){const vh=window.innerHeight||720,vw=window.innerWidth||1280,birds=[...document.querySelectorAll('.weather-fx-bird')].map(el=>el.getBoundingClientRect()).filter(r=>r.width>0&&r.top>vh*.42&&r.top<vh*.78);if(!birds.length)return null;const r=birds[Math.floor(Math.random()*birds.length)];return {x:sceneryClamp(r.left-55,8,vw-170,30),bottom:sceneryClamp(vh-r.bottom-12,18,vh*.34,28)};}
function dogSetPosition(node,target,duration=0){const rect=node.getBoundingClientRect(),currentX=rect.left||parseFloat(node.style.left)||0,nextX=Number(target.x);node.style.setProperty('--dog-facing',nextX<currentX?'-1':'1');node.style.setProperty('--dog-move-duration',`${Math.max(.25,duration).toFixed(2)}s`);node.style.left=`${Math.round(nextX)}px`;node.style.bottom=`${Math.round(target.bottom)}px`;}
function dogSetState(node,state){for(const cls of [...node.classList])if(cls.startsWith('dog-state-'))node.classList.remove(cls);node.classList.add(`dog-state-${state}`);node.dataset.dogState=state;dogRuntime.lastState=state;}
function dogNextState(node,source,birdsPresent,serial){if(serial!==dogRuntime.serial||!node?.isConnected)return;const activity=sceneryClamp(source.weatherDogActivity,40,160,100)/100,activeBias=sceneryClamp(.30+(activity-.4)*.29,.28,.67,.45),birdTarget=birdsPresent?lowBirdTarget():null,perch=dogPerchTarget(node);const rows=[['rest',18],['sit',17],['sleep',Math.max(8,20-activeBias*8)],['sniff',14],['wander',15+activeBias*15],['dig',5+activeBias*5],['roll',5+activeBias*4],['ball',5+activeBias*7]];if(birdTarget)rows.push(['bird',7+activeBias*6]);if(perch)rows.push(['perch',4+activeBias*3]);let state=choice(rows);if(state===dogRuntime.lastState&&Math.random()<.58)state=choice(rows.filter(r=>r[0]!==state));dogSetState(node,state);const vw=window.innerWidth||1280,vh=window.innerHeight||720,ground=sceneryClamp(vh*.035,18,54,28);let delay=rand(7,16)/Math.max(.65,Math.sqrt(activity));
  if(state==='wander'){const rect=node.getBoundingClientRect(),targetX=rand(vw*.035,vw*.86);const distance=Math.abs(targetX-rect.left),duration=sceneryClamp(distance/(45+activity*32),3.8,12,7);dogSetPosition(node,{x:targetX,bottom:ground+rand(-3,18)},duration);delay=duration+rand(1.5,4.5);}
  else if(state==='sniff'){const rect=node.getBoundingClientRect(),targetX=sceneryClamp(rect.left+rand(-vw*.10,vw*.10),8,vw-170,30),duration=sceneryClamp(Math.abs(targetX-rect.left)/65,1.4,4.8,2.5);dogSetPosition(node,{x:targetX,bottom:ground+rand(-2,7)},duration);delay=duration+rand(4,9);}
  else if(state==='ball'){const rect=node.getBoundingClientRect(),dir=rect.left>vw*.58?-1:1,targetX=sceneryClamp(rect.left+dir*rand(vw*.16,vw*.32),8,vw-170,30),duration=sceneryClamp(Math.abs(targetX-rect.left)/(70+activity*25),2.5,7,4);node.style.setProperty('--dog-ball-dir',String(dir));dogSetPosition(node,{x:targetX,bottom:ground+rand(-2,8)},duration);delay=duration+rand(3,7);}
  else if(state==='bird'&&birdTarget){const rect=node.getBoundingClientRect(),duration=sceneryClamp(Math.abs(birdTarget.x-rect.left)/78,2.2,6.5,4);dogSetPosition(node,birdTarget,duration);delay=duration+rand(3,7);}
  else if(state==='perch'&&perch){const rect=node.getBoundingClientRect(),duration=sceneryClamp(Math.hypot(perch.x-rect.left,perch.bottom-ground)/85,2.8,7.5,4.5);dogSetPosition(node,perch,duration);delay=duration+rand(8,18);}
  else if(state==='sleep'){delay=rand(18,36)/Math.max(.8,activity*.75);}
  else if(state==='sit'||state==='rest'){delay=rand(9,22)/Math.max(.8,activity*.78);}
  else if(state==='dig'||state==='roll'){delay=rand(6,11)/Math.max(.8,activity);}
  dogRuntime.timer=setTimeout(()=>dogNextState(node,source,birdsPresent,serial),Math.round(delay*1000));
}
function startDogRuntime(node,source,birdsPresent=false,reducedMotion=false){stopDogRuntime();dogRuntime.node=node;const serial=dogRuntime.serial;if(reducedMotion){dogSetState(node,'sit');return;}const vw=window.innerWidth||1280,vh=window.innerHeight||720;dogSetPosition(node,{x:rand(vw*.04,vw*.22),bottom:sceneryClamp(vh*.035,18,54,28)},.01);dogSetState(node,Math.random()<.5?'rest':'sit');dogRuntime.timer=setTimeout(()=>dogNextState(node,source,birdsPresent,serial),Math.round(rand(2500,6500)));}
function appendDogCompanion(frag,source,counts=null,reducedMotion=false){if(source.weatherDogCompanion!==true){stopDogRuntime();return false;}const breed=DOG_BREEDS.has(source.weatherDogBreed)?source.weatherDogBreed:'labrador',coat=LABRADOR_COATS.has(source.weatherDogLabradorCoat)?source.weatherDogLabradorCoat:'yellow',collar=DOG_COLLARS.has(source.weatherDogCollar)?source.weatherDogCollar:'blue',size=sceneryClamp(source.weatherDogSize,60,160,100)/100,opacity=sceneryClamp(source.weatherDogOpacity,20,100,100)/100,birds=Number(counts?.birds||0)+Number(counts?.owls||0),dog=document.createElement('span');dog.className=`weather-fx-dog weather-fx-dog-${breed}${breed==='labrador'?` weather-fx-dog-lab-${coat}`:''}${collar==='none'?' dog-collar-none':''}`;dog.dataset.breed=breed;dog.dataset.coat=coat;dog.dataset.collar=collar;dog.style.setProperty('--dog-size',size.toFixed(2));dog.style.setProperty('--dog-opacity',opacity.toFixed(2));dog.style.setProperty('--dog-collar',({red:'#c94045',blue:'#3478d4',teal:'#168f91',green:'#4d9b4d',purple:'#8057b2',pink:'#d65b8b',orange:'#df7d2c',black:'#22262c',brown:'#70492f'}[collar]||'#3478d4'));
  const figure=document.createElement('span');figure.className='dog-figure';for(const part of ['shadow','tail','tail-tip','body','back-mark','chest','neck-ruff','leg-rl','leg-rr','leg-fl','leg-fr','paw-rl','paw-rr','paw-fl','paw-fr','head','face-mark','ear-a','ear-b','muzzle','mouth','eye-a','eye-b','nose','collar','tag']){const el=document.createElement('i');el.className=`dog-${part}`;figure.appendChild(el);}dog.appendChild(figure);for(const [tag,cls] of [['b','dog-ball'],['em','dog-sleep'],['span','dog-dirt']]){const el=document.createElement(tag);el.className=cls;if(cls==='dog-sleep')el.textContent='z';dog.appendChild(el);}frag.appendChild(dog);requestAnimationFrame(()=>startDogRuntime(dog,source,birds>0,reducedMotion||dogReducedMotion(source)));return true;}
function dateFromWeather(data){const raw=String(data?.current?.time||'');const m=raw.match(/^(\d{4})-(\d{2})-(\d{2})/);if(m)return new Date(Date.UTC(+m[1],+m[2]-1,+m[3],12));const offset=Number(data?.utc_offset_seconds)||0;return new Date(Date.now()+offset*1000);}
function nthWeekday(year,month,weekday,n){const d=new Date(Date.UTC(year,month-1,1,12)),delta=(weekday-d.getUTCDay()+7)%7;return 1+delta+(n-1)*7;}
function lastWeekday(year,month,weekday){const d=new Date(Date.UTC(year,month,0,12));return d.getUTCDate()-((d.getUTCDay()-weekday+7)%7);}
function easterDate(year){let a=year%19,b=Math.floor(year/100),c=year%100,d=Math.floor(b/4),e=b%4,f=Math.floor((b+8)/25),g=Math.floor((b-f+1)/3),h=(19*a+b-d-g+15)%30,i=Math.floor(c/4),k=c%4,l=(32+2*e+2*i-h-k)%7,m=Math.floor((a+11*h+22*l)/451),month=Math.floor((h+l-7*m+114)/31),day=((h+l-7*m+114)%31)+1;return {month,day};}
function isHanukkah(date){try{const fmt=new Intl.DateTimeFormat('en-u-ca-hebrew',{month:'long',day:'numeric'});for(let ago=0;ago<8;ago++){const d=new Date(date.getTime()-ago*86400000),parts=fmt.formatToParts(d),month=parts.find(p=>p.type==='month')?.value?.toLowerCase()||'',day=Number(parts.find(p=>p.type==='day')?.value);if(month.includes('kislev')&&day===25)return true;}}catch{}const starts={2025:[12,14],2026:[12,4],2027:[12,24],2028:[12,12],2029:[12,1],2030:[12,20],2031:[12,9],2032:[11,27],2033:[12,16],2034:[12,6],2035:[12,25]};const s=starts[date.getUTCFullYear()];if(!s)return false;const start=Date.UTC(date.getUTCFullYear(),s[0]-1,s[1],12),delta=Math.floor((date.getTime()-start)/86400000);return delta>=0&&delta<8;}
function activeHolidayKeys(data,source){if(holidayTestProfile!=='live')return HOLIDAY_KEYS.includes(holidayTestProfile)?[holidayTestProfile]:[];if(source.holidayOverlaysEnabled!==true)return [];const date=dateFromWeather(data),y=date.getUTCFullYear(),m=date.getUTCMonth()+1,d=date.getUTCDate(),wd=date.getUTCDay(),enabled=k=>source[HOLIDAY_CONFIG[k]]!==false,out=[];const add=(k,yes)=>{if(yes&&enabled(k))out.push(k);};add('new-year',m===1&&d===1);add('valentines',m===2&&d===14);add('st-patrick',m===3&&d===17);const easter=easterDate(y);add('easter',m===easter.month&&d===easter.day);add('memorial',m===5&&d===lastWeekday(y,5,1));add('juneteenth',m===6&&d===19);add('independence',m===7&&d===4);add('labor',m===9&&d===nthWeekday(y,9,1,1));add('halloween',m===10&&d===31);add('day-of-dead',m===11&&(d===1||d===2));add('veterans',m===11&&d===11);add('thanksgiving',m===11&&d===nthWeekday(y,11,4,4));add('hanukkah',isHanukkah(date));add('christmas',m===12&&d===25);return out.slice(0,2);}
function holidayOverlayActive(source,data){return holidayTestProfile!=='live'||(source.holidayOverlaysEnabled===true&&activeHolidayKeys(data,source).length>0);}
function holidayNode(tag,cls){const el=document.createElement(tag);el.className=cls;return el;}
function appendHolidayOverlays(frag,source,data,constrained=false){const keys=activeHolidayKeys(data,source);if(!keys.length)return keys;const intensity=sceneryClamp(source.holidayOverlayIntensity,20,150,100)/100;for(const key of keys){const scene=holidayNode('span',`holiday-overlay holiday-overlay-${key}`);scene.dataset.holiday=key;scene.style.setProperty('--holiday-intensity',intensity.toFixed(2));const count=(n)=>Math.max(1,Math.round(n*(constrained?.55:1)*intensity));if(key==='christmas'){scene.appendChild(holidayNode('i','holiday-garland'));for(let i=0;i<count(14);i++){const light=holidayNode('b','holiday-light');light.style.setProperty('--holiday-i',String(i));scene.appendChild(light);}for(let i=0;i<count(6);i++){const gift=holidayNode('em','holiday-gift');gift.style.setProperty('--holiday-x',`${5+i*16+rand(-2,2)}vw`);gift.style.setProperty('--holiday-delay',`${-rand(0,5)}s`);scene.appendChild(gift);}}
    else if(key==='hanukkah'){const menorah=holidayNode('i','holiday-menorah');for(let i=0;i<9;i++){const candle=holidayNode('b','holiday-candle');candle.style.setProperty('--candle-i',String(i));menorah.appendChild(candle);}scene.appendChild(menorah);for(let i=0;i<count(18);i++){const star=holidayNode('em','holiday-sparkle');star.style.setProperty('--holiday-x',`${rand(2,98)}vw`);star.style.setProperty('--holiday-y',`${rand(4,80)}vh`);star.style.setProperty('--holiday-delay',`${-rand(0,7)}s`);scene.appendChild(star);}}
    else if(key==='independence'||key==='new-year'){for(let i=0;i<count(8);i++){const burst=holidayNode('i','holiday-firework');burst.style.setProperty('--holiday-x',`${rand(8,92)}vw`);burst.style.setProperty('--holiday-y',`${rand(8,55)}vh`);burst.style.setProperty('--holiday-delay',`${-rand(0,9)}s`);burst.style.setProperty('--holiday-hue',key==='independence'?(i%3===0?'0':i%3===1?'215':'0'):String(Math.round(rand(0,360))));scene.appendChild(burst);}for(let i=0;i<count(24);i++){const confetti=holidayNode('b','holiday-confetti');confetti.style.setProperty('--holiday-x',`${rand(0,100)}vw`);confetti.style.setProperty('--holiday-delay',`${-rand(0,8)}s`);scene.appendChild(confetti);}}
    else if(key==='halloween'){for(let i=0;i<count(5);i++){const pumpkin=holidayNode('i','holiday-pumpkin');pumpkin.style.setProperty('--holiday-x',`${4+i*21+rand(-3,3)}vw`);scene.appendChild(pumpkin);}for(let i=0;i<count(12);i++){const bat=holidayNode('b','holiday-bat');bat.style.setProperty('--holiday-y',`${rand(8,58)}vh`);bat.style.setProperty('--holiday-delay',`${-rand(0,9)}s`);scene.appendChild(bat);}}
    else if(key==='day-of-dead'){const banner=holidayNode('i','holiday-papel');scene.appendChild(banner);for(let i=0;i<count(22);i++){const petal=holidayNode('b','holiday-marigold');petal.style.setProperty('--holiday-x',`${rand(0,100)}vw`);petal.style.setProperty('--holiday-delay',`${-rand(0,10)}s`);scene.appendChild(petal);}scene.appendChild(holidayNode('em','holiday-calavera'));}
    else if(key==='thanksgiving'){for(let i=0;i<count(20);i++){const leaf=holidayNode('i','holiday-thanks-leaf');leaf.style.setProperty('--holiday-x',`${rand(0,100)}vw`);leaf.style.setProperty('--holiday-delay',`${-rand(0,10)}s`);scene.appendChild(leaf);}scene.appendChild(holidayNode('em','holiday-thanks-cornucopia'));}
    else if(key==='valentines'){for(let i=0;i<count(20);i++){const heart=holidayNode('i','holiday-heart');heart.style.setProperty('--holiday-x',`${rand(0,100)}vw`);heart.style.setProperty('--holiday-delay',`${-rand(0,11)}s`);scene.appendChild(heart);}}
    else if(key==='st-patrick'){for(let i=0;i<count(20);i++){const clover=holidayNode('i','holiday-clover');clover.style.setProperty('--holiday-x',`${rand(0,100)}vw`);clover.style.setProperty('--holiday-delay',`${-rand(0,11)}s`);scene.appendChild(clover);}}
    else if(key==='easter'){for(let i=0;i<count(9);i++){const egg=holidayNode('i','holiday-egg');egg.style.setProperty('--holiday-x',`${5+i*11+rand(-2,2)}vw`);egg.style.setProperty('--holiday-hue',String(Math.round(rand(0,360))));scene.appendChild(egg);}}
    else if(['memorial','veterans','juneteenth','labor'].includes(key)){const ribbon=holidayNode('i',`holiday-ribbon holiday-ribbon-${key}`);scene.appendChild(ribbon);for(let i=0;i<count(14);i++){const star=holidayNode('b','holiday-respect-star');star.style.setProperty('--holiday-x',`${rand(4,96)}vw`);star.style.setProperty('--holiday-y',`${rand(8,76)}vh`);star.style.setProperty('--holiday-delay',`${-rand(0,8)}s`);scene.appendChild(star);}}
    frag.appendChild(scene);}return keys;}
function holidayOverlayTestState(){return {active:holidayTestProfile!=='live',profile:holidayTestProfile,label:HOLIDAY_LABELS[holidayTestProfile]||'Calendar date'};}
function setHolidayOverlayTestProfile(value='live'){holidayTestProfile=HOLIDAY_KEYS.includes(value)?value:'live';const select=document.getElementById('s-holiday-overlay-test');if(select)select.value=holidayTestProfile;if(typeof holidayRefresh==='function')holidayRefresh();return holidayOverlayTestState();}
function registerHolidayRefresh(fn){holidayRefresh=typeof fn==='function'?fn:null;}
function initHolidayControls(){const select=document.getElementById('s-holiday-overlay-test'),preview=document.getElementById('s-holiday-overlay-preview'),stop=document.getElementById('s-holiday-overlay-stop');select?.addEventListener('change',()=>setHolidayOverlayTestProfile(select.value));preview?.addEventListener('click',()=>{if((select?.value||'live')==='live'){if(select)select.value='christmas';}setHolidayOverlayTestProfile(select?.value||'christmas');if(typeof globalThis.previewDashboardFromSettings==='function')globalThis.previewDashboardFromSettings();});stop?.addEventListener('click',()=>setHolidayOverlayTestProfile('live'));}
queueMicrotask(initHolidayControls);
LibreDisplayRuntime.exposeModule('weatherScenery',{DOG_BREEDS,LABRADOR_COATS,DOG_COLLARS,HOLIDAY_KEYS,HOLIDAY_CONFIG,HOLIDAY_LABELS,appendDogCompanion,stopDogRuntime,activeHolidayKeys,holidayOverlayActive,appendHolidayOverlays,holidayOverlayTestState,setHolidayOverlayTestProfile,registerHolidayRefresh},{},{globalFunctions:[],globalStates:[]});
