// Internal Arrange support for integration blocks.
// Plugins can expose stable section/subsection selectors through manifest.layoutParts.

const integrationsApi=LibreDisplayRuntime.getModule('integrations');
const blocksApi=LibreDisplayRuntime.getModule('blocks');
const layoutApi=LibreDisplayRuntime.getModule('layout');
const {escHtml}=LibreDisplayRuntime.getModule('shared');

const DEFAULT_PARTS={
  status:[
    {key:'primary',label:'Primary value',selector:'.integration-status-value',parent:'outer',order:10},
    {key:'provider',label:'Provider label',selector:'.integration-status-provider',parent:'outer',order:20},
    {key:'details',label:'Detail cards',selector:'.integration-status-details',parent:'outer',container:true,order:30},
  ],
  'now-playing':[
    {key:'art',label:'Artwork',selector:'.integration-now-art',parent:'outer',order:10},
    {key:'copy',label:'Track details',selector:'.integration-now-copy',parent:'outer',container:true,order:20},
  ],
  photos:[
    {key:'photo',label:'Photo',selector:'.integration-photo',parent:'outer',container:true,order:10},
    {key:'caption',label:'Photo caption',selector:'.integration-photo-caption',parent:'photo',order:10},
  ],
  tasks:[{key:'tasks',label:'Task list',selector:'.integration-task-list',parent:'outer',container:true,order:10}],
  messages:[{key:'messages',label:'Message list',selector:'.integration-messages',parent:'outer',container:true,order:10}],
  map:[{key:'map',label:'Map',selector:'.integration-map',parent:'outer',order:10}],
  data:[{key:'content',label:'Integration content',selector:'.integration-render-host,.custom-data-value,.custom-data-raw,.custom-rss-list',parent:'outer',container:true,order:10}],
};
const APPLIED_ATTR='data-ld-internal-layout-applied';
const TRACKED_STYLE_PROPS=['position','left','top','width','height','zIndex','order','display','flexDirection','flexWrap','gap','alignItems','justifyContent','minWidth','minHeight','maxWidth','maxHeight'];
const originalAppliedState=new WeakMap();
const watchedBlocks=new WeakMap();
let selectedBlockId='';
let selectedPartKey='';
let pointerState=null;
let refreshRaf=0;

function internalClamp(value,min,max,fallback=min){const n=Number(value);return Number.isFinite(n)?Math.max(min,Math.min(max,n)):fallback;}
function cleanKey(value){return String(value||'').replace(/[^A-Za-z0-9_-]/g,'').slice(0,64);}
function selectedIntegrationBlock(){const id=blocksApi.customKeyId(layoutApi.layoutSelectedKey);if(!id)return null;const block=blocksApi.customBlockById(id,blocksApi.layoutCustomBlocksDraft);return block?.type==='integration'?block:null;}
function blockElement(block){return block?document.querySelector(`.custom-block[data-block-id="${CSS.escape(block.id)}"]`):null;}
function manifestForBlock(block){return integrationsApi.integrationManifest(block?.config?.plugin)||null;}
function normalizePartDef(raw,index=0){if(!raw||typeof raw!=='object')return null;const key=cleanKey(raw.key);const selector=String(raw.selector||raw.selectors||'').trim();if(!key||!selector)return null;return {key,label:String(raw.label||key).slice(0,80),selector,parent:cleanKey(raw.parent),order:internalClamp(raw.order,-200,200,index*10),container:raw.container===true,movable:raw.movable!==false,root:raw.root===true};}
function integrationPartDefs(block,manifest=manifestForBlock(block)){
  const outer={key:'outer',label:'Integration canvas',selector:'.custom-block-card',parent:'',order:-100,container:true,movable:false,root:true};
  const title={key:'blockTitle',label:'Block title',selector:'.custom-block-title',parent:'outer',order:0,container:false,movable:true,root:false};
  const raw=Array.isArray(manifest?.layoutParts)&&manifest.layoutParts.length?manifest.layoutParts:(DEFAULT_PARTS[manifest?.kind]||DEFAULT_PARTS.data);
  const defs=[outer,title];let index=0;
  for(const item of raw){const def=normalizePartDef(item,index++);if(!def||defs.some(x=>x.key===def.key))continue;if(!def.parent)def.parent='outer';defs.push(def);}
  return defs;
}
function layoutStore(block,create=false){if(!block)return {};block.config=block.config||{};let store=block.config._internalLayout;if(!store||typeof store!=='object'||Array.isArray(store)){if(!create)return {};store={};block.config._internalLayout=store;}return store;}
function rowFor(block,key,create=false){const store=layoutStore(block,create);let row=store[key];if(!row||typeof row!=='object'||Array.isArray(row)){if(!create)return {};row={};store[key]=row;}return row;}
function normalizedRow(raw,def){const row=raw&&typeof raw==='object'?raw:{};return {mode:row.mode==='free'&&def?.movable!==false?'free':'flow',order:internalClamp(row.order,-200,200,def?.order||0),x:internalClamp(row.x,0,100,0),y:internalClamp(row.y,0,100,0),w:internalClamp(row.w,5,100,100),h:internalClamp(row.h,0,100,0),z:Math.round(internalClamp(row.z,0,99,0)),direction:['row','column'].includes(row.direction)?row.direction:'auto',gap:internalClamp(row.gap,0,60,8),align:['start','center','end','stretch'].includes(row.align)?row.align:'auto',justify:['start','center','end','space-between','space-around'].includes(row.justify)?row.justify:'auto'};}
function rowHasOverride(raw,def){if(!raw||typeof raw!=='object'||!Object.keys(raw).length)return false;const r=normalizedRow(raw,def);return r.mode==='free'||r.order!==(def?.order||0)||r.direction!=='auto'||r.gap!==8||r.align!=='auto'||r.justify!=='auto'||r.z!==0;}
function firstMatch(blockEl,def){if(!blockEl||!def)return null;try{return blockEl.querySelector(def.selector);}catch{return null;}}
function allMatches(blockEl,def){if(!blockEl||!def)return [];try{return [...blockEl.querySelectorAll(def.selector)];}catch{return [];}}
const markApplied=(el)=>{if(!el)return;if(!originalAppliedState.has(el))originalAppliedState.set(el,{styles:Object.fromEntries(TRACKED_STYLE_PROPS.map(prop=>[prop,el.style[prop]])),attr:el.getAttribute(APPLIED_ATTR),free:el.classList.contains('ld-internal-free-part'),flex:el.classList.contains('ld-internal-flex-container')});el.setAttribute(APPLIED_ATTR,'1');};
function clearAppliedStyles(blockEl){if(!blockEl)return;for(const el of blockEl.querySelectorAll(`[${APPLIED_ATTR}]`)){const state=originalAppliedState.get(el);if(state){for(const prop of TRACKED_STYLE_PROPS)el.style[prop]=state.styles[prop]||'';if(state.attr===null)el.removeAttribute(APPLIED_ATTR);else el.setAttribute(APPLIED_ATTR,state.attr);el.classList.toggle('ld-internal-free-part',state.free);el.classList.toggle('ld-internal-flex-container',state.flex);originalAppliedState.delete(el);}else{for(const prop of TRACKED_STYLE_PROPS)el.style[prop]='';el.removeAttribute(APPLIED_ATTR);el.classList.remove('ld-internal-free-part','ld-internal-flex-container');}}}
function cssAlign(value){return value==='start'?'flex-start':value==='end'?'flex-end':value;}
function applyContainerStyle(el,row,directionFallback='column'){if(!el)return;markApplied(el);const r=row||{};el.style.display='flex';el.style.flexDirection=r.direction==='row'?'row':r.direction==='column'?'column':directionFallback;el.style.flexWrap=el.style.flexDirection==='row'?'wrap':'nowrap';el.style.gap=`${internalClamp(r.gap,0,60,8)}px`;if(r.align!=='auto')el.style.alignItems=cssAlign(r.align);if(r.justify!=='auto')el.style.justifyContent=cssAlign(r.justify);el.classList.add('ld-internal-flex-container');}
function applyIntegrationInternalLayout(blockEl,block,manifest=manifestForBlock(block)){
  if(!blockEl||!block||block.type!=='integration')return;
  clearAppliedStyles(blockEl);
  const defs=integrationPartDefs(block,manifest),defMap=new Map(defs.map(d=>[d.key,d])),store=layoutStore(block,false);
  if(!Object.keys(store).length)return;
  const parentNeedsFlex=new Set(),parentNeedsPosition=new Set();
  for(const def of defs){const raw=store[def.key];if(!raw)continue;const row=normalizedRow(raw,def);if(def.container&&(row.direction!=='auto'||row.gap!==8||row.align!=='auto'||row.justify!=='auto'))parentNeedsFlex.add(def.key);if(def.parent&&(row.order!==def.order||row.mode==='flow'&&rowHasOverride(raw,def)))parentNeedsFlex.add(def.parent);if(def.parent&&row.mode==='free')parentNeedsPosition.add(def.parent);}
  for(const key of new Set([...parentNeedsFlex,...parentNeedsPosition])){const def=defMap.get(key);if(!def)continue;const el=firstMatch(blockEl,def);if(!el)continue;markApplied(el);el.style.position=el.style.position||'relative';if(parentNeedsFlex.has(key)){const row=normalizedRow(store[key],def);applyContainerStyle(el,row,'column');for(const childDef of defs.filter(x=>x.parent===key)){const childRow=normalizedRow(store[childDef.key],childDef);if(childRow.mode==='free')continue;for(const child of allMatches(blockEl,childDef)){markApplied(child);child.style.order=String(childRow.order);}}}}
  for(const def of defs){const raw=store[def.key];if(!raw)continue;const row=normalizedRow(raw,def);for(const el of allMatches(blockEl,def)){if(def.container&&(row.direction!=='auto'||row.gap!==8||row.align!=='auto'||row.justify!=='auto'))applyContainerStyle(el,row,'column');if(row.mode==='free'&&def.movable!==false){markApplied(el);el.style.position='absolute';el.style.left=`${row.x}%`;el.style.top=`${row.y}%`;el.style.width=`${row.w}%`;el.style.height=row.h>0?`${row.h}%`:'auto';el.style.zIndex=String(row.z||3);el.style.order='';el.classList.add('ld-internal-free-part');}else if(def.parent&&parentNeedsFlex.has(def.parent)){markApplied(el);el.style.order=String(row.order);}}}
}
function scheduleInspectorRefresh(){if(refreshRaf)return;refreshRaf=requestAnimationFrame(()=>{refreshRaf=0;refreshIntegrationInternalLayoutInspector();});}
function attachIntegrationLayout(blockEl,block,manifest=manifestForBlock(block)){if(!blockEl||!block)return;let record=watchedBlocks.get(blockEl);if(!record){record={block,manifest,scheduled:false};record.observer=new MutationObserver(()=>{if(record.scheduled)return;record.scheduled=true;queueMicrotask(()=>{record.scheduled=false;applyIntegrationInternalLayout(blockEl,record.block,record.manifest);if(layoutApi.layoutEditorActive&&blocksApi.customKeyId(layoutApi.layoutSelectedKey)===record.block.id)scheduleInspectorRefresh();});});record.observer.observe(blockEl,{childList:true,subtree:true});watchedBlocks.set(blockEl,record);}record.block=block;record.manifest=manifest;applyIntegrationInternalLayout(blockEl,block,manifest);if(layoutApi.layoutEditorActive&&blocksApi.customKeyId(layoutApi.layoutSelectedKey)===block.id)scheduleInspectorRefresh();}
function effectivePart(block,def){return normalizedRow(rowFor(block,def.key,false),def);}
function parentForDef(def,defs){return defs.find(x=>x.key===def.parent)||defs.find(x=>x.key==='outer')||null;}
function visiblePartElement(blockEl,def){for(const el of allMatches(blockEl,def)){const r=el.getBoundingClientRect();if(r.width>2&&r.height>2)return el;}return firstMatch(blockEl,def);}
function initialFreeGeometry(block,def,defs){const blockEl=blockElement(block),el=visiblePartElement(blockEl,def),parentDef=parentForDef(def,defs),parent=visiblePartElement(blockEl,parentDef);if(!el||!parent)return {x:0,y:0,w:100,h:0};const r=el.getBoundingClientRect(),p=parent.getBoundingClientRect();if(p.width<2||p.height<2)return {x:0,y:0,w:100,h:0};return {x:internalClamp((r.left-p.left)/p.width*100,0,100,0),y:internalClamp((r.top-p.top)/p.height*100,0,100,0),w:internalClamp(r.width/p.width*100,5,100,100),h:internalClamp(r.height/p.height*100,5,100,20)};}
function writeRow(block,key,patch){const defs=integrationPartDefs(block),def=defs.find(x=>x.key===key);if(!def)return null;const current=normalizedRow(rowFor(block,key,false),def),row=rowFor(block,key,true);Object.assign(row,current,patch);return normalizedRow(row,def);}
function commitAndRefresh(block){const el=blockElement(block);if(el)applyIntegrationInternalLayout(el,block,manifestForBlock(block));refreshIntegrationInternalLayoutInspector();}
function beginInternalChange(){if(layoutApi.layoutEditorActive)layoutApi.pushLayoutHistory();}
function setIntegrationInternalPart(key){const block=selectedIntegrationBlock(),defs=block?integrationPartDefs(block):[];selectedPartKey=defs.some(x=>x.key===key)?key:(defs.find(x=>x.key!=='outer'&&x.movable!==false)?.key||'outer');refreshIntegrationInternalLayoutInspector();}
function setIntegrationInternalMode(value){const block=selectedIntegrationBlock();if(!block)return;const defs=integrationPartDefs(block),def=defs.find(x=>x.key===selectedPartKey);if(!def||def.movable===false)return;beginInternalChange();if(value==='free'){const g=initialFreeGeometry(block,def,defs);writeRow(block,def.key,{mode:'free',...g});}else writeRow(block,def.key,{mode:'flow'});commitAndRefresh(block);}
function setIntegrationInternalGeometry(field,value){const block=selectedIntegrationBlock();if(!block||!['x','y','w','h','z'].includes(field))return;const def=integrationPartDefs(block).find(x=>x.key===selectedPartKey);if(!def||def.movable===false)return;beginInternalChange();let n=Number(value);if(field==='w')n=internalClamp(n,5,100,100);else if(field==='h')n=internalClamp(n,0,100,0);else if(field==='z')n=Math.round(internalClamp(n,0,99,0));else n=internalClamp(n,0,100,0);writeRow(block,def.key,{mode:'free',[field]:n});commitAndRefresh(block);}
function setIntegrationInternalDirection(value){const block=selectedIntegrationBlock();if(!block)return;const def=integrationPartDefs(block).find(x=>x.key===selectedPartKey);if(!def||!def.container)return;beginInternalChange();writeRow(block,def.key,{direction:['row','column'].includes(value)?value:'auto'});commitAndRefresh(block);}
function setIntegrationInternalGap(value){const block=selectedIntegrationBlock();if(!block)return;const def=integrationPartDefs(block).find(x=>x.key===selectedPartKey);if(!def||!def.container)return;beginInternalChange();writeRow(block,def.key,{gap:internalClamp(value,0,60,8)});commitAndRefresh(block);}
function setIntegrationInternalAlign(value){const block=selectedIntegrationBlock();if(!block)return;const def=integrationPartDefs(block).find(x=>x.key===selectedPartKey);if(!def||!def.container)return;beginInternalChange();writeRow(block,def.key,{align:['start','center','end','stretch'].includes(value)?value:'auto'});commitAndRefresh(block);}
function setIntegrationInternalJustify(value){const block=selectedIntegrationBlock();if(!block)return;const def=integrationPartDefs(block).find(x=>x.key===selectedPartKey);if(!def||!def.container)return;beginInternalChange();writeRow(block,def.key,{justify:['start','center','end','space-between','space-around'].includes(value)?value:'auto'});commitAndRefresh(block);}
function moveIntegrationInternalOrder(delta){const block=selectedIntegrationBlock();if(!block)return;const defs=integrationPartDefs(block),def=defs.find(x=>x.key===selectedPartKey);if(!def?.parent)return;const siblings=defs.filter(x=>x.parent===def.parent&&x.movable!==false).sort((a,b)=>effectivePart(block,a).order-effectivePart(block,b).order||a.order-b.order),index=siblings.findIndex(x=>x.key===def.key),target=siblings[index+(delta<0?-1:1)];if(index<0||!target)return;beginInternalChange();const a=effectivePart(block,def).order,b=effectivePart(block,target).order;writeRow(block,def.key,{order:b});writeRow(block,target.key,{order:a});commitAndRefresh(block);}
function placeIntegrationInternalPart(anchor){const block=selectedIntegrationBlock();if(!block)return;const defs=integrationPartDefs(block),def=defs.find(x=>x.key===selectedPartKey);if(!def||def.movable===false)return;beginInternalChange();let row=effectivePart(block,def);if(row.mode!=='free'){const g=initialFreeGeometry(block,def,defs);row=writeRow(block,def.key,{mode:'free',...g});}const xMap={left:0,center:(100-row.w)/2,right:100-row.w},yMap={top:0,middle:(100-(row.h||20))/2,bottom:100-(row.h||20)},[v,h]=String(anchor||'top-left').split('-');writeRow(block,def.key,{mode:'free',x:internalClamp(xMap[h]??xMap.center,0,100-row.w,0),y:internalClamp(yMap[v]??yMap.middle,0,100-(row.h||20),0)});commitAndRefresh(block);}
function resetIntegrationInternalPart(){const block=selectedIntegrationBlock();if(!block)return;beginInternalChange();const store=layoutStore(block,false);delete store[selectedPartKey];if(!Object.keys(store).length)delete block.config._internalLayout;commitAndRefresh(block);}
function resetIntegrationInternalLayout(){const block=selectedIntegrationBlock();if(!block||!block.config?._internalLayout)return;beginInternalChange();delete block.config._internalLayout;commitAndRefresh(block);}
function currentInternalSelection(){const block=selectedIntegrationBlock();if(!block)return null;const defs=integrationPartDefs(block),def=defs.find(x=>x.key===selectedPartKey)||defs.find(x=>x.key!=='outer'&&x.movable!==false)||defs[0];if(!def)return null;selectedPartKey=def.key;return {block,defs,def,row:effectivePart(block,def)};}
function refreshIntegrationInternalLayoutInspector(){const section=document.getElementById('layout-integration-internal-section'),selection=selectedIntegrationBlock();if(!section)return;if(!layoutApi.layoutEditorActive||!selection){section.hidden=true;selectedBlockId='';selectedPartKey='';renderIntegrationInternalPartBoxes();return;}section.hidden=false;const defs=integrationPartDefs(selection),blockChanged=selectedBlockId!==selection.id;selectedBlockId=selection.id;if(blockChanged||!defs.some(x=>x.key===selectedPartKey))selectedPartKey=defs.find(x=>x.key!=='outer'&&x.movable!==false)?.key||'outer';const info=currentInternalSelection();if(!info)return;const {def,row}=info,picker=document.getElementById('layout-integration-part-picker');if(picker){picker.innerHTML=defs.map(x=>`<option value="${escHtml(x.key)}">${escHtml(x.parent&&x.parent!=='outer'?'↳ '+x.label:x.label)}</option>`).join('');picker.value=def.key;}const parent=defs.find(x=>x.key===def.parent);const parentLabel=document.getElementById('layout-integration-parent-label');if(parentLabel)parentLabel.textContent=parent?`Inside ${parent.label}`:'Integration root';const mode=document.getElementById('layout-integration-mode');if(mode){mode.value=row.mode;mode.disabled=def.movable===false;}for(const field of ['x','y','w','h','z']){const input=document.getElementById('layout-integration-'+field);if(input){input.value=String(Math.round(row[field]*10)/10);input.disabled=def.movable===false||row.mode!=='free';}}const direction=document.getElementById('layout-integration-direction');if(direction){direction.value=row.direction;direction.disabled=!def.container;}const gap=document.getElementById('layout-integration-gap');if(gap){gap.value=String(row.gap);gap.disabled=!def.container;}const align=document.getElementById('layout-integration-align');if(align){align.value=row.align;align.disabled=!def.container;}const justify=document.getElementById('layout-integration-justify');if(justify){justify.value=row.justify;justify.disabled=!def.container;}document.getElementById('layout-integration-free-controls')?.toggleAttribute('hidden',row.mode!=='free'||def.movable===false);document.getElementById('layout-integration-container-controls')?.toggleAttribute('hidden',!def.container);renderIntegrationInternalPartBoxes();}
function renderIntegrationInternalPartBoxes(){const layer=document.getElementById('layout-editor-layer');if(!layer)return;for(const el of layer.querySelectorAll('.layout-internal-edit-box'))el.remove();if(!layoutApi.layoutEditorActive)return;const block=selectedIntegrationBlock();if(!block)return;const blockEl=blockElement(block);if(!blockEl)return;const defs=integrationPartDefs(block);for(const def of defs){if(def.key==='outer'||def.movable===false)continue;const part=visiblePartElement(blockEl,def);if(!part)continue;const rect=part.getBoundingClientRect();if(rect.width<4||rect.height<4)continue;const box=document.createElement('div');box.className='layout-internal-edit-box'+(def.key===selectedPartKey?' selected':'');box.dataset.integrationPart=def.key;Object.assign(box.style,{left:rect.left+'px',top:rect.top+'px',width:rect.width+'px',height:rect.height+'px'});box.innerHTML=`<div class="layout-internal-edit-label">${escHtml(def.label)}</div><div class="layout-internal-resize-handle" data-internal-resize="1" title="Resize this integration section"></div>`;box.addEventListener('pointerdown',beginIntegrationPartPointer);box.addEventListener('click',event=>{event.stopPropagation();setIntegrationInternalPart(def.key);});layer.appendChild(box);}}
function beginIntegrationPartPointer(event){const block=selectedIntegrationBlock();if(!block)return;const defs=integrationPartDefs(block),key=event.currentTarget.dataset.integrationPart,def=defs.find(x=>x.key===key);if(!def||def.movable===false)return;selectedPartKey=key;beginInternalChange();let row=effectivePart(block,def);if(row.mode!=='free'){const g=initialFreeGeometry(block,def,defs);row=writeRow(block,key,{mode:'free',...g});commitAndRefresh(block);}const parentDef=parentForDef(def,defs),parent=visiblePartElement(blockElement(block),parentDef),parentRect=parent?.getBoundingClientRect();if(!parentRect||parentRect.width<2||parentRect.height<2)return;pointerState={block,key,def,mode:event.target?.dataset?.internalResize?'resize':'move',pointerId:event.pointerId,startX:event.clientX,startY:event.clientY,parentRect,start:{...row}};event.currentTarget.setPointerCapture?.(event.pointerId);event.preventDefault();event.stopPropagation();}
function moveIntegrationPartPointer(event){const st=pointerState;if(!st||event.pointerId!==st.pointerId)return;const dx=(event.clientX-st.startX)/st.parentRect.width*100,dy=(event.clientY-st.startY)/st.parentRect.height*100;let patch;if(st.mode==='resize'){const w=internalClamp(st.start.w+dx,5,100-st.start.x,st.start.w),h=internalClamp((st.start.h||5)+dy,5,100-st.start.y,st.start.h||5);patch={mode:'free',w,h};}else{patch={mode:'free',x:internalClamp(st.start.x+dx,0,100-st.start.w,st.start.x),y:internalClamp(st.start.y+dy,0,100-(st.start.h||5),st.start.y)};}writeRow(st.block,st.key,patch);const el=blockElement(st.block);if(el)applyIntegrationInternalLayout(el,st.block,manifestForBlock(st.block));renderIntegrationInternalPartBoxes();refreshIntegrationInternalLayoutInspectorValuesOnly();event.preventDefault();}
function endIntegrationPartPointer(event){if(pointerState&&(!event||event.pointerId===pointerState.pointerId)){pointerState=null;scheduleInspectorRefresh();}}
function refreshIntegrationInternalLayoutInspectorValuesOnly(){const info=currentInternalSelection();if(!info)return;const {def,row}=info;for(const field of ['x','y','w','h','z']){const input=document.getElementById('layout-integration-'+field);if(input&&!input.matches(':focus'))input.value=String(Math.round(row[field]*10)/10);}const mode=document.getElementById('layout-integration-mode');if(mode)mode.value=row.mode;document.getElementById('layout-integration-free-controls')?.toggleAttribute('hidden',row.mode!=='free'||def.movable===false);}

function scheduleSelectionAwareRefresh(){if(layoutApi.layoutEditorActive)scheduleInspectorRefresh();}
document.addEventListener('click',event=>{if(event.target?.closest?.('.layout-edit-box,#layout-toolbar,#layout-properties'))scheduleSelectionAwareRefresh();});
document.addEventListener('change',event=>{if(event.target?.closest?.('#layout-toolbar,#layout-properties'))scheduleSelectionAwareRefresh();});
document.addEventListener('keyup',scheduleSelectionAwareRefresh);
window.addEventListener('resize',scheduleSelectionAwareRefresh);
new MutationObserver(scheduleSelectionAwareRefresh).observe(document.body,{attributes:true,attributeFilter:['class']});
document.addEventListener('pointermove',moveIntegrationPartPointer,{passive:false});
document.addEventListener('pointerup',event=>{endIntegrationPartPointer(event);scheduleSelectionAwareRefresh();});

LibreDisplayRuntime.exposeModule('layout',{integrationPartDefs,applyIntegrationInternalLayout,attachIntegrationLayout,setIntegrationInternalPart,setIntegrationInternalMode,setIntegrationInternalGeometry,setIntegrationInternalDirection,setIntegrationInternalGap,setIntegrationInternalAlign,setIntegrationInternalJustify,moveIntegrationInternalOrder,placeIntegrationInternalPart,resetIntegrationInternalPart,resetIntegrationInternalLayout,refreshIntegrationInternalLayoutInspector,renderIntegrationInternalPartBoxes}, {}, {globals:false});
