// Layout preset gallery and live preset preview pipeline.
const configApi=LibreDisplayRuntime.getModule('config');
const {integrationManifest}=LibreDisplayRuntime.getModule('integrations');
const {renderCalendar}=LibreDisplayRuntime.getModule('calendar');
const {renderWeather}=LibreDisplayRuntime.getModule('weather');
const {escHtml}=LibreDisplayRuntime.getModule('shared');


const LAYOUT_PRESET_ORDER=['current','family','split','gallery','calendar','agenda','weather','morning','smarthub','familyops','office','insights','travel','large','compact','minimal','portrait','portraitphoto','default'];
const LAYOUT_PRESET_LABELS={calendar:'CAL',current:'WX',clock:'TIME',details:'INFO',daily:'DAYS',hourly:'HOURS',alerts:'ALERT'};
const BALANCED_LAYOUT_THUMBNAIL={
  calendar:{x:.02,y:.03,w:.96,h:.18},alerts:{x:.22,y:.28,w:.56,h:.22},current:{x:.03,y:.68,w:.15,h:.22},clock:{x:.20,y:.67,w:.23,h:.20},details:{x:.03,y:.91,w:.40,h:.07},daily:{x:.47,y:.68,w:.50,h:.12},hourly:{x:.47,y:.83,w:.50,h:.12}
};
const LAYOUT_PRESETS={
  family:{name:'Family Command Center',category:'Family',bestFor:'Landscape · busy households',featured:true,description:'A structured family dashboard with a generous week planner, a calm time/weather rail, and balanced forecasts along the footer.',mode:'custom',view:{calendarDays:7,calendarColumns:4,calendarMaxEvents:3,calendarCellHeight:160,dailyForecastDays:7,hourlyForecastHours:9},contentScale:{calendar:112,current:110,clock:112,details:100,daily:104,hourly:104,alerts:96},partStyle:{calendar:{dayLabel:{scale:94},eventTime:{scale:94}},current:{condition:{scale:96}},clock:{seconds:{scale:90}}},elementStyle:{calendar:{hAlign:'left',vAlign:'top'},clock:{hAlign:'right',vAlign:'middle'},current:{hAlign:'right',vAlign:'middle'},details:{hAlign:'right',vAlign:'middle'},daily:{hAlign:'center',vAlign:'middle'},hourly:{hAlign:'center',vAlign:'middle'}},blocks:{calendar:{x:.035,y:.055,w:.615,h:.39},clock:{x:.69,y:.055,w:.275,h:.19},current:{x:.69,y:.265,w:.275,h:.27},details:{x:.69,y:.565,w:.275,h:.12},alerts:{x:.12,y:.50,w:.50,h:.10},daily:{x:.035,y:.735,w:.445,h:.16},hourly:{x:.52,y:.735,w:.445,h:.16}}},
  split:{name:'Photo + Planner',category:'Photo',bestFor:'Landscape · photo + calendar',featured:true,description:'A refined split screen with a quiet photo field on the left, a strong planner column on the right, and matching forecast rows below.',mode:'custom',photoZone:{x:.035,y:.235,w:.305,h:.35},view:{calendarDays:7,calendarColumns:4,calendarMaxEvents:3,calendarCellHeight:180,dailyForecastDays:7,hourlyForecastHours:9},contentScale:{calendar:100,current:112,clock:116,details:100,daily:100,hourly:100,alerts:94},partStyle:{calendar:{dayLabel:{scale:92},eventTime:{scale:92}},clock:{seconds:{scale:90}},current:{condition:{scale:96}}},elementStyle:{clock:{hAlign:'left',vAlign:'middle'},current:{hAlign:'left',vAlign:'middle'},details:{hAlign:'left',vAlign:'middle'},calendar:{hAlign:'left',vAlign:'top'},daily:{hAlign:'center',vAlign:'middle'},hourly:{hAlign:'center',vAlign:'middle'}},blocks:{clock:{x:.035,y:.05,w:.305,h:.18},current:{x:.035,y:.60,w:.305,h:.25},details:{x:.035,y:.87,w:.305,h:.095},calendar:{x:.395,y:.05,w:.57,h:.46},alerts:{x:.45,y:.525,w:.46,h:.09},daily:{x:.395,y:.64,w:.57,h:.13},hourly:{x:.395,y:.81,w:.57,h:.13}}},
  gallery:{name:'Gallery Week',category:'Photo',bestFor:'Widescreen · photo first',featured:true,description:'A photo-first composition with balanced corner anchors, a clean week band, and evenly weighted forecast rows.',mode:'custom',photoZone:{x:.305,y:.09,w:.39,h:.37},view:{calendarDays:7,calendarColumns:7,calendarMaxEvents:3,calendarCellHeight:170,dailyForecastDays:7,hourlyForecastHours:9},contentScale:{calendar:100,current:110,clock:118,details:96,daily:102,hourly:102,alerts:92},partStyle:{calendar:{dayLabel:{scale:94},eventTime:{scale:92}},clock:{seconds:{scale:88}},current:{condition:{scale:94}}},elementStyle:{clock:{hAlign:'left',vAlign:'middle'},current:{hAlign:'right',vAlign:'middle'},details:{hAlign:'right',vAlign:'middle'},calendar:{hAlign:'left',vAlign:'top'},daily:{hAlign:'center',vAlign:'middle'},hourly:{hAlign:'center',vAlign:'middle'}},blocks:{clock:{x:.035,y:.05,w:.265,h:.18},current:{x:.73,y:.05,w:.235,h:.245},details:{x:.70,y:.315,w:.265,h:.105},alerts:{x:.31,y:.47,w:.38,h:.09},calendar:{x:.035,y:.565,w:.93,h:.22},daily:{x:.035,y:.815,w:.445,h:.13},hourly:{x:.52,y:.815,w:.445,h:.13}}},
  calendar:{name:'Calendar Wall',category:'Calendar',bestFor:'Wall display · week at a glance',featured:true,description:'A true calendar-first wall view with a larger week canvas and a disciplined lower information shelf instead of scattered blocks.',mode:'custom',view:{calendarDays:7,calendarColumns:7,calendarMaxEvents:4,calendarCellHeight:240,dailyForecastDays:7,hourlyForecastHours:9},contentScale:{calendar:120,current:112,clock:118,details:100,daily:104,hourly:104,alerts:98},partStyle:{calendar:{dayLabel:{scale:94},eventTime:{scale:96}},clock:{seconds:{scale:90}},current:{condition:{scale:96}}},elementStyle:{calendar:{hAlign:'left',vAlign:'top'},clock:{hAlign:'left',vAlign:'middle'},current:{hAlign:'left',vAlign:'middle'},details:{hAlign:'left',vAlign:'middle'},daily:{hAlign:'center',vAlign:'middle'},hourly:{hAlign:'center',vAlign:'middle'}},blocks:{calendar:{x:.035,y:.045,w:.93,h:.44},alerts:{x:.25,y:.505,w:.50,h:.09},clock:{x:.035,y:.635,w:.215,h:.185},current:{x:.275,y:.625,w:.215,h:.225},details:{x:.035,y:.855,w:.455,h:.105},daily:{x:.525,y:.625,w:.44,h:.14},hourly:{x:.525,y:.805,w:.44,h:.14}}},
  agenda:{name:'Planner + Weather Rail',category:'Planner',bestFor:'Landscape · event-heavy homes',description:'A planner-led composition with a broad readable schedule, a deliberately spaced weather rail, and forecasts spanning the footer.',mode:'custom',view:{calendarDays:6,calendarColumns:3,calendarMaxEvents:4,calendarCellHeight:200,dailyForecastDays:7,hourlyForecastHours:9},contentScale:{calendar:110,current:108,clock:112,details:98,daily:102,hourly:102,alerts:94},partStyle:{calendar:{dayLabel:{scale:94},eventTime:{scale:96}},clock:{seconds:{scale:90}},current:{condition:{scale:96}}},elementStyle:{calendar:{hAlign:'left',vAlign:'top'},clock:{hAlign:'right',vAlign:'middle'},current:{hAlign:'right',vAlign:'middle'},details:{hAlign:'right',vAlign:'middle'},daily:{hAlign:'center',vAlign:'middle'},hourly:{hAlign:'center',vAlign:'middle'}},blocks:{calendar:{x:.035,y:.05,w:.625,h:.51},clock:{x:.70,y:.05,w:.265,h:.18},current:{x:.70,y:.255,w:.265,h:.27},details:{x:.70,y:.555,w:.265,h:.125},alerts:{x:.12,y:.59,w:.49,h:.09},daily:{x:.035,y:.755,w:.445,h:.15},hourly:{x:.52,y:.755,w:.445,h:.15}}},
  weather:{name:'Weather Center',category:'Weather',bestFor:'Forecast-heavy displays',description:'A weather-led dashboard with a larger current-conditions column, paired forecast bands, and a secondary planner that still reads cleanly.',mode:'custom',view:{calendarDays:5,calendarColumns:5,calendarMaxEvents:2,calendarCellHeight:180,dailyForecastDays:7,hourlyForecastHours:9},contentScale:{calendar:98,current:126,clock:116,details:108,daily:110,hourly:110,alerts:96},partStyle:{calendar:{dayLabel:{scale:94},eventTime:{scale:92}},clock:{seconds:{scale:88}},current:{condition:{scale:100}}},elementStyle:{current:{hAlign:'left',vAlign:'middle'},clock:{hAlign:'left',vAlign:'middle'},details:{hAlign:'left',vAlign:'middle'},calendar:{hAlign:'left',vAlign:'top'},daily:{hAlign:'center',vAlign:'middle'},hourly:{hAlign:'center',vAlign:'middle'}},blocks:{current:{x:.035,y:.07,w:.285,h:.32},clock:{x:.035,y:.425,w:.285,h:.18},details:{x:.035,y:.635,w:.285,h:.14},daily:{x:.365,y:.065,w:.60,h:.18},hourly:{x:.365,y:.285,w:.60,h:.18},calendar:{x:.365,y:.525,w:.60,h:.27},alerts:{x:.25,y:.835,w:.50,h:.09}}},
  morning:{name:'Morning Briefing',category:'Showcase',bestFor:'Kitchen · before-work glance',featured:true,description:'A crisp morning command center that pairs the day’s schedule and weather with dedicated commute and task slots.',mode:'custom',view:{calendarDays:5,calendarColumns:5,calendarMaxEvents:2,calendarCellHeight:130,dailyForecastDays:5,hourlyForecastHours:6},contentScale:{calendar:104,current:112,clock:118,details:96,daily:98,hourly:98,alerts:92},partStyle:{calendar:{dayLabel:{scale:94},eventTime:{scale:94}},clock:{seconds:{scale:88}},current:{condition:{scale:96}}},elementStyle:{clock:{hAlign:'left',vAlign:'middle'},current:{hAlign:'left',vAlign:'middle'},details:{hAlign:'left',vAlign:'middle'},calendar:{hAlign:'left',vAlign:'top'},daily:{hAlign:'center',vAlign:'middle'},hourly:{hAlign:'center',vAlign:'middle'}},blocks:{clock:{x:.035,y:.05,w:.24,h:.17},current:{x:.035,y:.25,w:.24,h:.25},details:{x:.035,y:.53,w:.24,h:.12},daily:{x:.035,y:.69,w:.24,h:.20},calendar:{x:.31,y:.05,w:.655,h:.31},alerts:{x:.39,y:.39,w:.49,h:.07},hourly:{x:.31,y:.49,w:.655,h:.13}},showcaseSlots:[{id:'commute',label:'Commute',icon:'↗',value:'23 min',sub:'Traffic-aware route or next transit arrivals',hint:'Mapbox Travel · GTFS-Realtime',plugins:['mapbox-travel','gtfs-realtime'],rect:{x:.31,y:.66,w:.31,h:.28}},{id:'tasks',label:'Today',icon:'✓',value:'3 things left',sub:'Tasks, errands, or morning routines',hint:'Todoist · Google Tasks · Microsoft To Do',kinds:['tasks'],types:['todo'],rect:{x:.655,y:.66,w:.31,h:.28}}]},
  smarthub:{name:'Smart Home Hub',category:'Showcase',bestFor:'Living room · connected home',featured:true,description:'A connected-home canvas with weather and schedule anchors plus generous slots for smart-home state, music, tasks, messages, and a map.',mode:'custom',view:{calendarDays:2,calendarColumns:1,calendarMaxEvents:2,calendarCellHeight:92,dailyForecastDays:3,hourlyForecastHours:4,showHourlyForecast:false},contentScale:{calendar:94,current:108,clock:116,details:92,daily:90,hourly:90,alerts:90},partStyle:{calendar:{dayLabel:{scale:90},eventTime:{scale:90}},clock:{seconds:{scale:88}},current:{condition:{scale:94}}},elementStyle:{clock:{hAlign:'left',vAlign:'middle'},current:{hAlign:'left',vAlign:'middle'},details:{hAlign:'left',vAlign:'middle'},calendar:{hAlign:'left',vAlign:'top'},daily:{hAlign:'center',vAlign:'middle'},hourly:{hAlign:'center',vAlign:'middle'}},blocks:{clock:{x:.035,y:.05,w:.25,h:.15},current:{x:.035,y:.22,w:.25,h:.21},details:{x:.035,y:.45,w:.25,h:.10},daily:{x:.035,y:.58,w:.25,h:.13},calendar:{x:.035,y:.74,w:.25,h:.19},hourly:{x:.035,y:.95,w:.25,h:.025},alerts:{x:.33,y:.90,w:.635,h:.075}},showcaseSlots:[{id:'home',label:'Home',icon:'⌂',value:'Living room · 72°',sub:'Surface a favorite Home Assistant entity at a glance',hint:'Home Assistant',plugins:['home-assistant'],rect:{x:.33,y:.05,w:.30,h:.25}},{id:'media',label:'Now Playing',icon:'♪',value:'Kitchen speaker',sub:'Album art and current track from your music system',hint:'Spotify · Sonos',kinds:['now-playing'],rect:{x:.665,y:.05,w:.30,h:.25}},{id:'tasks',label:'Household',icon:'✓',value:'4 open items',sub:'Shared tasks or a local family checklist',hint:'Tasks · Family Chores',kinds:['tasks'],types:['todo','family'],rect:{x:.33,y:.34,w:.30,h:.26}},{id:'messages',label:'Updates',icon:'#',value:'3 new messages',sub:'Recent household or team messages',hint:'Slack · RSS',kinds:['messages'],types:['rss'],rect:{x:.665,y:.34,w:.30,h:.26}},{id:'map',label:'Around Home',icon:'⌖',value:'Neighborhood',sub:'Map, school route, or a frequently checked location',hint:'OpenStreetMap',kinds:['map'],rect:{x:.33,y:.64,w:.635,h:.22}}]},
  familyops:{name:'Family Operations',category:'Showcase',bestFor:'Busy family · shared routines',featured:true,description:'A family-focused board with a strong shared calendar plus chore, task, delivery, and commute slots for the information that drives the day.',mode:'custom',view:{calendarDays:7,calendarColumns:4,calendarMaxEvents:3,calendarCellHeight:150,dailyForecastDays:5,hourlyForecastHours:6,showDailyForecast:false,showHourlyForecast:false},contentScale:{calendar:108,current:108,clock:114,details:94,daily:92,hourly:92,alerts:92},partStyle:{calendar:{dayLabel:{scale:94},eventTime:{scale:94}},clock:{seconds:{scale:88}},current:{condition:{scale:94}}},elementStyle:{calendar:{hAlign:'left',vAlign:'top'},clock:{hAlign:'right',vAlign:'middle'},current:{hAlign:'right',vAlign:'middle'},details:{hAlign:'right',vAlign:'middle'}},blocks:{calendar:{x:.035,y:.05,w:.60,h:.40},clock:{x:.675,y:.05,w:.29,h:.17},current:{x:.675,y:.25,w:.29,h:.23},details:{x:.675,y:.50,w:.29,h:.09},alerts:{x:.675,y:.60,w:.29,h:.08},daily:{x:.675,y:.70,w:.29,h:.08},hourly:{x:.675,y:.80,w:.29,h:.08}},showcaseSlots:[{id:'chores',label:'Chores',icon:'★',value:'12 points today',sub:'Household chores, rewards, and touch completion',hint:'LibreDisplay Family Chores',types:['family'],rect:{x:.035,y:.50,w:.285,h:.43}},{id:'tasks',label:'Shared Tasks',icon:'✓',value:'5 left this week',sub:'A family task list from the service you already use',hint:'Todoist · Google Tasks · Microsoft To Do',kinds:['tasks'],types:['todo'],rect:{x:.35,y:.50,w:.285,h:.43}},{id:'delivery',label:'Deliveries',icon:'▰',value:'2 arriving today',sub:'Package status without opening another app',hint:'AfterShip',plugins:['aftership'],rect:{x:.675,y:.70,w:.29,h:.10}},{id:'commute',label:'Next Trip',icon:'↗',value:'18 min',sub:'Traffic-aware travel time or transit arrivals',hint:'Mapbox · GTFS-Realtime',plugins:['mapbox-travel','gtfs-realtime'],rect:{x:.675,y:.83,w:.29,h:.10}}]},
  office:{name:'Team Board',category:'Showcase',bestFor:'Office · studio · team space',description:'An office-ready information board that combines the shared schedule with messages, work queues, news, and a metric card.',mode:'custom',view:{calendarDays:5,calendarColumns:2,calendarMaxEvents:4,calendarCellHeight:150,dailyForecastDays:3,hourlyForecastHours:3},contentScale:{calendar:102,current:102,clock:110,details:90,daily:88,hourly:88,alerts:88},partStyle:{calendar:{dayLabel:{scale:94},eventTime:{scale:94}},clock:{seconds:{scale:86}},current:{condition:{scale:92}}},elementStyle:{clock:{hAlign:'left',vAlign:'middle'},current:{hAlign:'left',vAlign:'middle'},details:{hAlign:'left',vAlign:'middle'},calendar:{hAlign:'left',vAlign:'top'},daily:{hAlign:'center',vAlign:'middle'},hourly:{hAlign:'center',vAlign:'middle'}},blocks:{clock:{x:.035,y:.05,w:.22,h:.15},current:{x:.035,y:.22,w:.22,h:.20},details:{x:.035,y:.44,w:.22,h:.11},daily:{x:.275,y:.05,w:.18,h:.15},hourly:{x:.275,y:.22,w:.18,h:.15},alerts:{x:.275,y:.44,w:.18,h:.11},calendar:{x:.035,y:.60,w:.42,h:.33}},showcaseSlots:[{id:'messages',label:'Team Updates',icon:'#',value:'3 recent messages',sub:'A compact communication stream for the room',hint:'Slack Messages',kinds:['messages'],rect:{x:.49,y:.05,w:.475,h:.35}},{id:'work',label:'Work Queue',icon:'✓',value:'7 active items',sub:'Project tasks and cards that need attention',hint:'Asana · Trello · Todoist',kinds:['tasks'],rect:{x:.49,y:.44,w:.23,h:.49}},{id:'news',label:'News',icon:'≋',value:'Latest headlines',sub:'Company news, industry updates, or an internal feed',hint:'RSS / Atom',types:['rss'],rect:{x:.735,y:.44,w:.23,h:.23}},{id:'metric',label:'Metric',icon:'↗',value:'98.4%',sub:'A KPI, API value, chart, or system status',hint:'Web API · JSON / Data',plugins:['web-api'],types:['json'],rect:{x:.735,y:.70,w:.23,h:.23}}]},
  insights:{name:'Markets & Conditions',category:'Showcase',bestFor:'Data wall · personal dashboard',description:'A compact data wall for market snapshots, environmental conditions, a chart, and headlines without losing time, weather, or schedule context.',mode:'custom',view:{calendarDays:4,calendarColumns:1,calendarMaxEvents:2,calendarCellHeight:105,dailyForecastDays:4,hourlyForecastHours:4},contentScale:{calendar:94,current:104,clock:110,details:90,daily:92,hourly:92,alerts:88},partStyle:{calendar:{dayLabel:{scale:92},eventTime:{scale:90}},clock:{seconds:{scale:86}},current:{condition:{scale:92}}},elementStyle:{clock:{hAlign:'left',vAlign:'middle'},current:{hAlign:'left',vAlign:'middle'},details:{hAlign:'left',vAlign:'middle'},calendar:{hAlign:'left',vAlign:'top'},daily:{hAlign:'center',vAlign:'middle'},hourly:{hAlign:'center',vAlign:'middle'}},blocks:{clock:{x:.035,y:.05,w:.22,h:.15},current:{x:.035,y:.22,w:.22,h:.22},details:{x:.035,y:.46,w:.22,h:.10},calendar:{x:.035,y:.60,w:.22,h:.33},daily:{x:.30,y:.66,w:.315,h:.13},hourly:{x:.65,y:.66,w:.315,h:.13},alerts:{x:.30,y:.83,w:.665,h:.09}},showcaseSlots:[{id:'stock',label:'Market',icon:'$',value:'+0.6% today',sub:'A favorite stock quote and daily change',hint:'Alpha Vantage',plugins:['alpha-vantage'],rect:{x:.30,y:.05,w:.20,h:.19}},{id:'crypto',label:'Crypto',icon:'₿',value:'24h +1.8%',sub:'A crypto price snapshot in your preferred currency',hint:'CoinGecko',plugins:['coingecko'],rect:{x:.52,y:.05,w:.20,h:.19}},{id:'conditions',label:'Conditions',icon:'☀',value:'UV 4 · Moderate',sub:'UV, pollen, air quality, tides, or a personal weather station',hint:'Open-Meteo · Google Pollen · NOAA',plugins:['open-meteo-uv','google-pollen','noaa-tides','weather-company-pws','fitbit'],types:['airquality'],rect:{x:.74,y:.05,w:.225,h:.19}},{id:'chart',label:'Trend',icon:'⌁',value:'Live data',sub:'Turn an API response into a chart, gauge, progress bar, or table',hint:'JSON / Data · Web API',plugins:['web-api'],types:['json'],rect:{x:.30,y:.29,w:.435,h:.32}},{id:'news',label:'Headlines',icon:'≋',value:'What’s happening',sub:'A narrow news rail for the latest items',hint:'RSS / Atom',types:['rss'],rect:{x:.76,y:.29,w:.205,h:.32}}]},
  travel:{name:'Travel Day',category:'Showcase',bestFor:'Trips · pickups · commute',description:'A travel-focused screen with flight, route, and map slots surrounded by compact weather and schedule context for the day ahead.',mode:'custom',view:{calendarDays:4,calendarColumns:1,calendarMaxEvents:3,calendarCellHeight:110,dailyForecastDays:5,hourlyForecastHours:6},contentScale:{calendar:96,current:106,clock:112,details:92,daily:94,hourly:94,alerts:90},partStyle:{calendar:{dayLabel:{scale:92},eventTime:{scale:92}},clock:{seconds:{scale:88}},current:{condition:{scale:94}}},elementStyle:{clock:{hAlign:'left',vAlign:'middle'},current:{hAlign:'left',vAlign:'middle'},details:{hAlign:'left',vAlign:'middle'},calendar:{hAlign:'left',vAlign:'top'},daily:{hAlign:'center',vAlign:'middle'},hourly:{hAlign:'center',vAlign:'middle'}},blocks:{clock:{x:.035,y:.05,w:.23,h:.15},current:{x:.035,y:.23,w:.23,h:.21},details:{x:.035,y:.46,w:.23,h:.10},calendar:{x:.035,y:.60,w:.23,h:.33},daily:{x:.30,y:.05,w:.315,h:.13},hourly:{x:.65,y:.05,w:.315,h:.13},alerts:{x:.35,y:.205,w:.565,h:.08}},showcaseSlots:[{id:'flight',label:'Flight',icon:'✈',value:'On time',sub:'Status, schedule, and reported delay for a flight',hint:'aviationstack',plugins:['aviationstack'],rect:{x:.30,y:.32,w:.315,h:.17}},{id:'commute',label:'Travel Time',icon:'↗',value:'26 min',sub:'Traffic-aware drive time or next transit arrivals',hint:'Mapbox · GTFS-Realtime',plugins:['mapbox-travel','gtfs-realtime'],rect:{x:.65,y:.32,w:.315,h:.17}},{id:'map',label:'Route Area',icon:'⌖',value:'Destination',sub:'Keep a frequently checked destination visible on the wall',hint:'OpenStreetMap',kinds:['map'],rect:{x:.30,y:.53,w:.665,h:.40}}]},
  large:{name:'Across the Room',category:'Readable',bestFor:'TV · longer viewing distance',description:'A distance-readable layout with fewer, larger calendar and forecast columns so the screen stays legible instead of merely scaled up.',mode:'custom',view:{calendarDays:5,calendarColumns:5,calendarMaxEvents:2,calendarCellHeight:190,dailyForecastDays:5,hourlyForecastHours:6},contentScale:{calendar:132,current:136,clock:138,details:116,daily:114,hourly:114,alerts:106},partStyle:{calendar:{dayLabel:{scale:96},eventTime:{scale:100}},clock:{seconds:{scale:88}},current:{condition:{scale:102}}},elementStyle:{clock:{hAlign:'left',vAlign:'middle'},current:{hAlign:'right',vAlign:'middle'},details:{hAlign:'left',vAlign:'middle'},calendar:{hAlign:'left',vAlign:'top'},daily:{hAlign:'center',vAlign:'middle'},hourly:{hAlign:'center',vAlign:'middle'}},blocks:{calendar:{x:.035,y:.045,w:.93,h:.27},alerts:{x:.25,y:.335,w:.50,h:.06},clock:{x:.035,y:.41,w:.36,h:.22},current:{x:.605,y:.405,w:.36,h:.245},details:{x:.035,y:.68,w:.36,h:.11},daily:{x:.44,y:.68,w:.525,h:.115},hourly:{x:.44,y:.825,w:.525,h:.115}}},
  compact:{name:'Countertop Grid',category:'Compact',bestFor:'Tablet · 16:10 · small monitor',description:'A compact two-column grid with tuned content density, stronger alignment, and useful breathing room for custom blocks below.',mode:'custom',view:{calendarDays:5,calendarColumns:5,calendarMaxEvents:2,calendarCellHeight:165,dailyForecastDays:5,hourlyForecastHours:6},contentScale:{calendar:96,current:102,clock:104,details:92,daily:94,hourly:94,alerts:90},partStyle:{calendar:{dayLabel:{scale:92},eventTime:{scale:92}},clock:{seconds:{scale:88}},current:{condition:{scale:94}}},elementStyle:{calendar:{hAlign:'left',vAlign:'top'},clock:{hAlign:'right',vAlign:'middle'},current:{hAlign:'right',vAlign:'middle'},details:{hAlign:'right',vAlign:'middle'},daily:{hAlign:'center',vAlign:'middle'},hourly:{hAlign:'center',vAlign:'middle'}},blocks:{calendar:{x:.035,y:.045,w:.585,h:.30},clock:{x:.67,y:.045,w:.295,h:.16},current:{x:.67,y:.235,w:.295,h:.245},details:{x:.67,y:.505,w:.295,h:.12},daily:{x:.035,y:.405,w:.585,h:.13},hourly:{x:.035,y:.565,w:.585,h:.13},alerts:{x:.13,y:.73,w:.49,h:.085}}},
  minimal:{name:'Minimal Photo',category:'Minimal',bestFor:'Photo frame · calm spaces',featured:true,description:'A calmer photo-frame layout with stronger corner anchors and a restrained five-day footer that leaves the center truly open.',mode:'custom',photoZone:{x:.245,y:.20,w:.51,h:.44},view:{calendarDays:5,calendarColumns:5,calendarMaxEvents:1,calendarCellHeight:115,dailyForecastDays:5,hourlyForecastHours:6},contentScale:{calendar:92,current:112,clock:126,details:92,daily:92,hourly:92,alerts:88},partStyle:{calendar:{dayLabel:{scale:90},eventTime:{scale:90}},clock:{seconds:{scale:86}},current:{condition:{scale:94}}},elementStyle:{clock:{hAlign:'left',vAlign:'middle'},current:{hAlign:'right',vAlign:'middle'},details:{hAlign:'right',vAlign:'middle'},calendar:{hAlign:'left',vAlign:'top'},daily:{hAlign:'center',vAlign:'middle'},hourly:{hAlign:'center',vAlign:'middle'}},blocks:{clock:{x:.035,y:.05,w:.30,h:.18},current:{x:.735,y:.05,w:.23,h:.245},details:{x:.70,y:.315,w:.265,h:.105},alerts:{x:.35,y:.655,w:.30,h:.075},calendar:{x:.035,y:.745,w:.565,h:.18},daily:{x:.645,y:.74,w:.32,h:.095},hourly:{x:.645,y:.85,w:.32,h:.105}}},
  portrait:{name:'Portrait Planner',category:'Portrait',bestFor:'Vertical wall display · tablet',description:'A genuinely vertical planner: time and weather form a compact header, the schedule wraps into readable rows, and forecasts anchor the lower screen.',mode:'custom',view:{calendarDays:6,calendarColumns:2,calendarMaxEvents:3,calendarCellHeight:180,dailyForecastDays:5,hourlyForecastHours:6},contentScale:{calendar:102,current:110,clock:114,details:96,daily:100,hourly:100,alerts:90},partStyle:{calendar:{dayLabel:{scale:96},eventTime:{scale:96}},clock:{seconds:{scale:88}},current:{condition:{scale:96}}},elementStyle:{clock:{hAlign:'left',vAlign:'middle'},current:{hAlign:'right',vAlign:'middle'},details:{hAlign:'center',vAlign:'middle'},calendar:{hAlign:'left',vAlign:'top'},daily:{hAlign:'center',vAlign:'middle'},hourly:{hAlign:'center',vAlign:'middle'}},blocks:{clock:{x:.06,y:.04,w:.40,h:.11},current:{x:.54,y:.04,w:.40,h:.145},details:{x:.06,y:.19,w:.88,h:.075},calendar:{x:.06,y:.285,w:.88,h:.32},alerts:{x:.15,y:.62,w:.70,h:.04},daily:{x:.06,y:.67,w:.88,h:.09},hourly:{x:.06,y:.79,w:.88,h:.09}}},
  portraitphoto:{name:'Portrait Gallery',category:'Portrait',bestFor:'Vertical display · photo first',description:'A portrait photo composition with a balanced information header, a two-row planner, and compact forecast cards that no longer feel detached.',mode:'custom',photoZone:{x:.06,y:.17,w:.42,h:.29},view:{calendarDays:5,calendarColumns:3,calendarMaxEvents:2,calendarCellHeight:180,dailyForecastDays:5,hourlyForecastHours:6},contentScale:{calendar:96,current:106,clock:112,details:92,daily:96,hourly:96,alerts:88},partStyle:{calendar:{dayLabel:{scale:94},eventTime:{scale:94}},clock:{seconds:{scale:88}},current:{condition:{scale:94}}},elementStyle:{clock:{hAlign:'left',vAlign:'middle'},current:{hAlign:'right',vAlign:'middle'},details:{hAlign:'right',vAlign:'middle'},calendar:{hAlign:'left',vAlign:'top'},daily:{hAlign:'center',vAlign:'middle'},hourly:{hAlign:'center',vAlign:'middle'}},blocks:{clock:{x:.06,y:.04,w:.40,h:.105},current:{x:.54,y:.04,w:.40,h:.145},details:{x:.54,y:.20,w:.40,h:.075},calendar:{x:.06,y:.50,w:.88,h:.255},alerts:{x:.18,y:.775,w:.64,h:.055},daily:{x:.06,y:.85,w:.42,h:.08},hourly:{x:.52,y:.85,w:.42,h:.08}}},
  default:{name:'Libre Balanced',category:'Classic',bestFor:'General landscape use',description:'The original LibreDisplay composition with a wide calendar band and familiar weather/forecast regions.',mode:'default',blocks:{},contentScale:{},elementStyle:{},thumbnail:BALANCED_LAYOUT_THUMBNAIL}
};
let settingsLayoutPresetKey='current';
function cloneLayoutPresetValue(v){return JSON.parse(JSON.stringify(v));}
function currentLayoutPresetThumbnail(){
  if(cfg.layoutMode==='custom'&&cfg.layoutBlocks&&Object.keys(cfg.layoutBlocks).length)return cfg.layoutBlocks;
  return BALANCED_LAYOUT_THUMBNAIL;
}
function layoutPresetThumbnailBlocks(key){
  if(key==='current')return currentLayoutPresetThumbnail();
  const preset=LAYOUT_PRESETS[key];return preset?.thumbnail||preset?.blocks||BALANCED_LAYOUT_THUMBNAIL;
}
function layoutPresetBlockHtml(key,r){
  if(!r||![r.x,r.y,r.w,r.h].every(v=>Number.isFinite(Number(v))))return '';
  const left=Math.max(0,Math.min(100,Number(r.x)*100)),top=Math.max(0,Math.min(100,Number(r.y)*100)),width=Math.max(2,Math.min(100-left,Number(r.w)*100)),height=Math.max(2,Math.min(100-top,Number(r.h)*100));
  return `<span class="layout-preset-block" data-layout-block="${escHtml(key)}" style="left:${left.toFixed(2)}%;top:${top.toFixed(2)}%;width:${width.toFixed(2)}%;height:${height.toFixed(2)}%">${escHtml(LAYOUT_PRESET_LABELS[key]||key)}</span>`;
}
function layoutPresetPhotoZoneHtml(zone){
  if(!zone||![zone.x,zone.y,zone.w,zone.h].every(v=>Number.isFinite(Number(v))))return '';
  const left=Math.max(0,Math.min(100,Number(zone.x)*100)),top=Math.max(0,Math.min(100,Number(zone.y)*100)),width=Math.max(2,Math.min(100-left,Number(zone.w)*100)),height=Math.max(2,Math.min(100-top,Number(zone.h)*100));
  return `<span class="layout-preset-photo-zone" style="left:${left.toFixed(2)}%;top:${top.toFixed(2)}%;width:${width.toFixed(2)}%;height:${height.toFixed(2)}%">photo</span>`;
}
function layoutPresetShowcaseSlotHtml(slot){
  const r=slot?.rect;if(!r||![r.x,r.y,r.w,r.h].every(v=>Number.isFinite(Number(v))))return '';
  const left=Math.max(0,Math.min(100,Number(r.x)*100)),top=Math.max(0,Math.min(100,Number(r.y)*100)),width=Math.max(2,Math.min(100-left,Number(r.w)*100)),height=Math.max(2,Math.min(100-top,Number(r.h)*100));
  return `<span class="layout-preset-block layout-preset-showcase" style="left:${left.toFixed(2)}%;top:${top.toFixed(2)}%;width:${width.toFixed(2)}%;height:${height.toFixed(2)}%">${escHtml(slot.label||'APP')}</span>`;
}
function layoutPresetCardHtml(key){
  const current=key==='current',preset=current?null:LAYOUT_PRESETS[key],name=current?'Current saved layout':preset.name,description=current?(cfg.layoutMode==='custom'?'Your saved custom Arrange layout.':'Your saved Libre Balanced layout.'):preset.description;
  const blocks=layoutPresetThumbnailBlocks(key),photo=current?'':layoutPresetPhotoZoneHtml(preset?.photoZone),showcase=current?'':(preset?.showcaseSlots||[]).map(layoutPresetShowcaseSlotHtml).join(''),thumb=photo+Object.entries(blocks).map(([block,r])=>layoutPresetBlockHtml(block,r)).join('')+showcase;
  const selected=settingsLayoutPresetKey===key,showcaseLayout=!!preset?.showcaseSlots?.length;
  const meta=current?'<span class="layout-preset-badge">Saved</span>':`<span class="layout-preset-badge${preset.featured?' featured':''}">${escHtml(showcaseLayout?'Integration showcase':preset.featured?'Featured':preset.category||'Layout')}</span><span class="layout-preset-badge">${escHtml(preset.bestFor||'Flexible')}</span>`;
  const tip=current?'Choose another card to stage a new arrangement. Nothing changes until you save.':showcaseLayout?'Compatible configured blocks snap into the labeled slots during preview; empty slots demonstrate integrations you can add.':'Select to stage it, then use Preview selected layout for a full-screen live preview.';
  return `<button class="layout-preset-card${selected?' selected':''}" data-layout-preset="${escHtml(key)}" type="button" role="radio" aria-checked="${selected?'true':'false'}" onclick="selectLayoutPreset('${escHtml(key)}')"><span class="layout-preset-stage" aria-hidden="true">${thumb}</span><span class="layout-preset-copy"><b>${escHtml(name)}</b><span>${escHtml(description)}</span><span class="layout-preset-meta">${meta}</span><small>${escHtml(tip)}</small></span></button>`;
}
function layoutShowcaseSlotMatches(block,slot){
  if(!block||!slot)return false;
  if((slot.types||[]).includes(block.type))return true;
  if(block.type!=='integration')return false;
  const plugin=String(block.config?.plugin||'');if((slot.plugins||[]).includes(plugin))return true;
  const kind=integrationManifest(plugin)?.kind||'';return !!kind&&(slot.kinds||[]).includes(kind);
}
function stageLayoutShowcaseBlocks(blocks,slots){
  const staged=cloneLayoutPresetValue(Array.isArray(blocks)?blocks:[]),filled=[],used=new Set();
  for(const slot of slots||[]){
    const index=staged.findIndex((block,i)=>!used.has(i)&&layoutShowcaseSlotMatches(block,slot));if(index<0)continue;
    const block=staged[index];block.rect=cloneLayoutPresetValue(slot.rect);block.config=block.config&&typeof block.config==='object'?{...block.config}:{};
    if(Number.isFinite(Number(slot.scale)))block.config._contentScale=Math.max(50,Math.min(160,Number(slot.scale)));
    used.add(index);filled.push(slot.id);
  }
  return {blocks:staged,filled};
}
function renderLayoutShowcase(source=cfg){
  const layer=document.getElementById('layout-showcase-layer');if(!layer)return;layer.innerHTML='';
  const slots=Array.isArray(source?._layoutShowcaseSlots)?source._layoutShowcaseSlots:[];if(!slots.length)return;
  const filled=new Set(Array.isArray(source?._layoutShowcaseFilledSlots)?source._layoutShowcaseFilledSlots:[]);
  for(const slot of slots){
    if(filled.has(slot.id)||!validStoredLayoutRect(slot.rect))continue;
    const r=slot.rect,el=document.createElement('div'),pixelH=window.innerHeight*Number(r.h),pixelW=window.innerWidth*Number(r.w),compact=Number(r.h)<.14||pixelH<118||pixelW<230;el.className='layout-showcase-placeholder'+(compact?' compact':'');
    el.style.left=(Number(r.x)*100).toFixed(3)+'%';el.style.top=(Number(r.y)*100).toFixed(3)+'%';el.style.width=(Number(r.w)*100).toFixed(3)+'%';el.style.height=(Number(r.h)*100).toFixed(3)+'%';
    el.innerHTML=`<div class="layout-showcase-head"><span class="layout-showcase-icon">${escHtml(slot.icon||'◇')}</span><span class="layout-showcase-title">${escHtml(slot.label||'Integration')}</span><span class="layout-showcase-chip">preview</span></div><div><div class="layout-showcase-value">${escHtml(slot.value||'Live data')}</div><div class="layout-showcase-sub">${escHtml(slot.sub||'Add a compatible block to fill this slot.')}</div></div><div class="layout-showcase-hint">${escHtml(slot.hint||'Add from Arrange → Add Block')}</div>`;
    layer.appendChild(el);
  }
}
function renderLayoutPresetGallery(){
  const host=document.getElementById('layout-preset-gallery');if(!host)return;
  host.innerHTML=LAYOUT_PRESET_ORDER.map(layoutPresetCardHtml).join('');
  const status=document.getElementById('layout-preset-status');if(status){const preset=LAYOUT_PRESETS[settingsLayoutPresetKey];status.textContent=settingsLayoutPresetKey==='current'?'Current saved layout selected. Choose a preset to stage a different arrangement.':`Previewing ${preset?.name||'layout'} — not saved yet.`;}
}
function applyLayoutPresetToSource(source,key=settingsLayoutPresetKey,options={}){
  if(!source||key==='current')return source;
  const preset=LAYOUT_PRESETS[key];if(!preset)return source;
  source.layoutMode=preset.mode==='custom'?'custom':'default';
  source.layoutBlocks=preset.mode==='custom'?cloneLayoutPresetValue(preset.blocks||{}):{};
  source.layoutContentScale=cloneLayoutPresetValue(preset.contentScale||{});
  source.layoutElementStyle=cloneLayoutPresetValue(preset.elementStyle||{});
  source.layoutPartStyle=cloneLayoutPresetValue(preset.partStyle||{});
  if(preset.view&&typeof preset.view==='object')Object.assign(source,cloneLayoutPresetValue(preset.view));
  if(Array.isArray(preset.showcaseSlots)&&preset.showcaseSlots.length){
    const staged=stageLayoutShowcaseBlocks(source.customBlocks||[],preset.showcaseSlots);source.customBlocks=staged.blocks;
    if(options.preview){source._layoutShowcaseSlots=cloneLayoutPresetValue(preset.showcaseSlots);source._layoutShowcaseFilledSlots=staged.filled;}
  }
  return source;
}
function selectLayoutPreset(key){
  if(key!=='current'&&!LAYOUT_PRESETS[key])return;
  settingsLayoutPresetKey=key;
  previewAppearance();
  renderLayoutPresetGallery();
  markSettingsDirty();
}
function previewSelectedLayoutFromSettings(){
  previewAppearance();
  previewDashboardFromSettings();
}
function previewAppearance(){
  const temp=applyLayoutPresetToSource(appearanceFromForm(),settingsLayoutPresetKey,{preview:true});
  updateFontPreview();
  window.__uiPreviewCfg=temp;
  updateAppearanceLabels(temp);
  applyUiCustomization(temp);
  if(configApi.wxData)renderWeather(configApi.wxData);
  renderCalendar(window.__lastCalendarEvents||[]);
}


// Preserve compatibility with existing inline event wiring while callers migrate to module APIs.
LibreDisplayRuntime.exposeModule("appearance", {cloneLayoutPresetValue,currentLayoutPresetThumbnail,layoutPresetThumbnailBlocks,layoutPresetBlockHtml,layoutPresetPhotoZoneHtml,layoutPresetShowcaseSlotHtml,layoutPresetCardHtml,layoutShowcaseSlotMatches,stageLayoutShowcaseBlocks,renderLayoutShowcase,renderLayoutPresetGallery,applyLayoutPresetToSource,selectLayoutPreset,previewSelectedLayoutFromSettings,previewAppearance}, {
  "LAYOUT_PRESET_ORDER": {configurable:true,get:()=>LAYOUT_PRESET_ORDER},
  "LAYOUT_PRESET_LABELS": {configurable:true,get:()=>LAYOUT_PRESET_LABELS},
  "BALANCED_LAYOUT_THUMBNAIL": {configurable:true,get:()=>BALANCED_LAYOUT_THUMBNAIL},
  "LAYOUT_PRESETS": {configurable:true,get:()=>LAYOUT_PRESETS},
  "settingsLayoutPresetKey": {configurable:true,get:()=>settingsLayoutPresetKey,set:(value)=>{settingsLayoutPresetKey=value;}}
}, {globalFunctions:['renderLayoutShowcase','renderLayoutPresetGallery','applyLayoutPresetToSource','selectLayoutPreset','previewSelectedLayoutFromSettings','previewAppearance'],globalStates:[]});
