// Granular weather-effect tuning form helpers.
const WEATHER_TUNING_DEFAULTS={
  weatherRainWidth:100,weatherRainSpeed:100,weatherRainOpacity:100,weatherRainAngle:100,weatherRainDepth:100,weatherRainSplashSize:100,weatherRainGlow:100,
  weatherSnowSpeed:100,weatherSnowOpacity:100,weatherSnowSpin:100,weatherSnowDepth:100,
  weatherFogOpacity:100,weatherFogBlur:100,weatherFogLayerHeight:100,weatherFogRollingBanks:true,weatherStormCloudDeck:true,weatherStormRainSheets:true,weatherLightningStreaks:true,weatherSnowBlowing:true,
  weatherCloudDensity:100,weatherCloudOpacity:100,weatherCloudSpeed:100,weatherCloudScale:100,weatherSunGlow:100,weatherSunRaySpeed:100,weatherLightningSize:100,weatherLightningFlash:100,weatherLightningBolts:100,
  weatherSeasonLeavesSize:100,weatherSeasonLeavesSpeed:100,weatherSeasonLeavesWind:100,weatherSeasonLeavesOpacity:100,
  weatherSeasonGrassHeight:100,weatherSeasonGrassSway:100,weatherSeasonGrassOpacity:100,
  weatherSeasonPetalSize:100,weatherSeasonPetalSpeed:100,weatherSeasonPetalOpacity:100,
  weatherSeasonBees:true,weatherSeasonBeeIntensity:55,weatherSeasonBeeSize:100,weatherSeasonBeeSpeed:100,weatherSeasonBeeOpacity:100,weatherSeasonButterflies:true,weatherSeasonButterflyIntensity:50,weatherSeasonButterflySize:100,weatherSeasonButterflySpeed:100,weatherSeasonButterflyOpacity:100,weatherSeasonButterflyDiversity:75,weatherSeasonFireflies:true,weatherSeasonFireflyIntensity:70,weatherSeasonFireflySize:100,weatherSeasonFireflySpeed:100,weatherSeasonFireflyGlow:100,weatherSeasonFireflyOpacity:100,
  weatherSeasonBirds:true,weatherSeasonBirdIntensity:55,weatherSeasonBirdSize:100,weatherSeasonBirdSpeed:100,weatherSeasonBirdFlock:60,weatherSeasonBirdOpacity:100,weatherSeasonBirdHeight:100,weatherSeasonBirdDiversity:72,weatherSeasonBirdRare:30,weatherSeasonOwls:false,weatherSeasonOwlIntensity:45,weatherSeasonOwlSize:110,weatherSeasonOwlSpeed:85,weatherSeasonOwlOpacity:100,weatherSeasonOwlDiversity:75,weatherSeasonDragonflies:true,weatherSeasonDragonflyIntensity:35,weatherSeasonDragonflySize:100,weatherSeasonDragonflySpeed:110,weatherSeasonDragonflyOpacity:100,weatherSeasonLadybugs:true,weatherSeasonLadybugIntensity:25,weatherSeasonLadybugSize:100,weatherSeasonLadybugSpeed:80,weatherSeasonLadybugOpacity:100,weatherSeasonMoths:true,weatherSeasonMothIntensity:40,weatherSeasonMothSize:100,weatherSeasonMothSpeed:90,weatherSeasonMothOpacity:100,weatherSeasonCrystals:true,weatherSeasonCrystalIntensity:70,weatherSeasonCrystalSize:100,weatherSeasonCrystalSpeed:100,weatherSeasonCrystalOpacity:100,weatherColdFrostWidth:100,weatherColdFrostOpacity:100
};
const WEATHER_TUNING_FIELDS=[
  ['s-weather-rain-width','weatherRainWidth'],['s-weather-rain-speed','weatherRainSpeed'],['s-weather-rain-opacity','weatherRainOpacity'],['s-weather-rain-angle','weatherRainAngle'],['s-weather-rain-depth','weatherRainDepth'],['s-weather-rain-splash-size','weatherRainSplashSize'],['s-weather-rain-glow','weatherRainGlow'],
  ['s-weather-snow-speed','weatherSnowSpeed'],['s-weather-snow-opacity','weatherSnowOpacity'],['s-weather-snow-spin','weatherSnowSpin'],['s-weather-snow-depth','weatherSnowDepth'],
  ['s-weather-fog-opacity','weatherFogOpacity'],['s-weather-fog-blur','weatherFogBlur'],['s-weather-fog-layer-height','weatherFogLayerHeight'],
  ['s-weather-cloud-density','weatherCloudDensity'],['s-weather-cloud-opacity','weatherCloudOpacity'],['s-weather-cloud-speed','weatherCloudSpeed'],['s-weather-cloud-scale','weatherCloudScale'],['s-weather-sun-glow','weatherSunGlow'],['s-weather-sun-ray-speed','weatherSunRaySpeed'],['s-weather-lightning-size','weatherLightningSize'],['s-weather-lightning-flash','weatherLightningFlash'],['s-weather-lightning-bolts','weatherLightningBolts'],
  ['s-weather-leaves-size','weatherSeasonLeavesSize'],['s-weather-leaves-speed','weatherSeasonLeavesSpeed'],['s-weather-leaves-wind','weatherSeasonLeavesWind'],['s-weather-leaves-opacity','weatherSeasonLeavesOpacity'],
  ['s-weather-grass-height','weatherSeasonGrassHeight'],['s-weather-grass-sway','weatherSeasonGrassSway'],['s-weather-grass-opacity','weatherSeasonGrassOpacity'],
  ['s-weather-petal-size','weatherSeasonPetalSize'],['s-weather-petal-speed','weatherSeasonPetalSpeed'],['s-weather-petal-opacity','weatherSeasonPetalOpacity'],
  ['s-weather-bee-intensity','weatherSeasonBeeIntensity'],['s-weather-bee-size','weatherSeasonBeeSize'],['s-weather-bee-speed','weatherSeasonBeeSpeed'],['s-weather-bee-opacity','weatherSeasonBeeOpacity'],['s-weather-butterfly-intensity','weatherSeasonButterflyIntensity'],['s-weather-butterfly-size','weatherSeasonButterflySize'],['s-weather-butterfly-speed','weatherSeasonButterflySpeed'],['s-weather-butterfly-opacity','weatherSeasonButterflyOpacity'],['s-weather-butterfly-diversity','weatherSeasonButterflyDiversity'],['s-weather-firefly-intensity','weatherSeasonFireflyIntensity'],['s-weather-firefly-size','weatherSeasonFireflySize'],['s-weather-firefly-speed','weatherSeasonFireflySpeed'],['s-weather-firefly-glow','weatherSeasonFireflyGlow'],['s-weather-firefly-opacity','weatherSeasonFireflyOpacity'],['s-weather-bird-intensity','weatherSeasonBirdIntensity'],['s-weather-bird-size','weatherSeasonBirdSize'],['s-weather-bird-speed','weatherSeasonBirdSpeed'],['s-weather-bird-flock','weatherSeasonBirdFlock'],['s-weather-bird-opacity','weatherSeasonBirdOpacity'],['s-weather-bird-height','weatherSeasonBirdHeight'],['s-weather-bird-diversity','weatherSeasonBirdDiversity'],['s-weather-bird-rare','weatherSeasonBirdRare'],['s-weather-owl-intensity','weatherSeasonOwlIntensity'],['s-weather-owl-size','weatherSeasonOwlSize'],['s-weather-owl-speed','weatherSeasonOwlSpeed'],['s-weather-owl-opacity','weatherSeasonOwlOpacity'],['s-weather-owl-diversity','weatherSeasonOwlDiversity'],['s-weather-dragonfly-intensity','weatherSeasonDragonflyIntensity'],['s-weather-dragonfly-size','weatherSeasonDragonflySize'],['s-weather-dragonfly-speed','weatherSeasonDragonflySpeed'],['s-weather-dragonfly-opacity','weatherSeasonDragonflyOpacity'],['s-weather-ladybug-intensity','weatherSeasonLadybugIntensity'],['s-weather-ladybug-size','weatherSeasonLadybugSize'],['s-weather-ladybug-speed','weatherSeasonLadybugSpeed'],['s-weather-ladybug-opacity','weatherSeasonLadybugOpacity'],['s-weather-moth-intensity','weatherSeasonMothIntensity'],['s-weather-moth-size','weatherSeasonMothSize'],['s-weather-moth-speed','weatherSeasonMothSpeed'],['s-weather-moth-opacity','weatherSeasonMothOpacity'],['s-weather-crystal-intensity','weatherSeasonCrystalIntensity'],['s-weather-crystal-size','weatherSeasonCrystalSize'],['s-weather-crystal-speed','weatherSeasonCrystalSpeed'],['s-weather-crystal-opacity','weatherSeasonCrystalOpacity'],['s-weather-cold-frost-width','weatherColdFrostWidth'],['s-weather-cold-frost-opacity','weatherColdFrostOpacity']
];
const WEATHER_TUNING_CHECKS=[['s-weather-fog-rolling-banks','weatherFogRollingBanks'],['s-weather-storm-cloud-deck','weatherStormCloudDeck'],['s-weather-storm-rain-sheets','weatherStormRainSheets'],['s-weather-lightning-streaks','weatherLightningStreaks'],['s-weather-snow-blowing','weatherSnowBlowing'],['s-weather-season-bees','weatherSeasonBees'],['s-weather-season-butterflies','weatherSeasonButterflies'],['s-weather-season-fireflies','weatherSeasonFireflies'],['s-weather-season-dragonflies','weatherSeasonDragonflies'],['s-weather-season-ladybugs','weatherSeasonLadybugs'],['s-weather-season-moths','weatherSeasonMoths'],['s-weather-season-birds','weatherSeasonBirds'],['s-weather-season-owls','weatherSeasonOwls'],['s-weather-season-crystals','weatherSeasonCrystals']];
const WEATHER_TUNING_KEYS=[...Object.keys(WEATHER_TUNING_DEFAULTS)];

const WEATHER_DEPENDENT_CONTROLS={
  's-weather-rain-enabled':['s-weather-rain-density','s-weather-rain-size','s-weather-rain-width','s-weather-rain-speed','s-weather-rain-opacity','s-weather-rain-angle','s-weather-rain-depth','s-weather-rain-splash','s-weather-rain-splash-size','s-weather-rain-glow'],
  's-weather-snow-enabled':['s-weather-snow-blowing','s-weather-snow-density','s-weather-snow-size','s-weather-snow-drift','s-weather-snow-speed','s-weather-snow-opacity','s-weather-snow-spin','s-weather-snow-depth'],
  's-weather-effect-fog':['s-weather-fog-rolling-banks','s-weather-fog-density','s-weather-fog-speed','s-weather-fog-opacity','s-weather-fog-blur','s-weather-fog-layer-height'],
  's-weather-effect-clouds':['s-weather-cloud-density','s-weather-cloud-opacity','s-weather-cloud-speed','s-weather-cloud-scale'],
  's-weather-effect-sun':['s-weather-sun-glow','s-weather-sun-ray-speed'],
  's-weather-effect-lightning':['s-weather-lightning-streaks','s-weather-effect-lightning-frequency','s-weather-effect-lightning-brightness','s-weather-lightning-size','s-weather-lightning-flash','s-weather-lightning-bolts'],
  's-weather-season-leaves':['s-weather-leaves-intensity','s-weather-leaves-size','s-weather-leaves-speed','s-weather-leaves-wind','s-weather-leaves-opacity'],
  's-weather-season-grass':['s-weather-grass-intensity','s-weather-grass-height','s-weather-grass-sway','s-weather-grass-opacity'],
  's-weather-season-petals':['s-weather-petal-intensity','s-weather-petal-size','s-weather-petal-speed','s-weather-petal-opacity'],
  's-weather-season-bees':['s-weather-bee-intensity','s-weather-bee-size','s-weather-bee-speed','s-weather-bee-opacity'],
  's-weather-season-butterflies':['s-weather-butterfly-intensity','s-weather-butterfly-size','s-weather-butterfly-speed','s-weather-butterfly-opacity','s-weather-butterfly-diversity'],
  's-weather-season-fireflies':['s-weather-firefly-intensity','s-weather-firefly-size','s-weather-firefly-speed','s-weather-firefly-glow','s-weather-firefly-opacity'],
  's-weather-season-dragonflies':['s-weather-dragonfly-intensity','s-weather-dragonfly-size','s-weather-dragonfly-speed','s-weather-dragonfly-opacity'],
  's-weather-season-ladybugs':['s-weather-ladybug-intensity','s-weather-ladybug-size','s-weather-ladybug-speed','s-weather-ladybug-opacity'],
  's-weather-season-moths':['s-weather-moth-intensity','s-weather-moth-size','s-weather-moth-speed','s-weather-moth-opacity'],
  's-weather-season-birds':['s-weather-bird-habitat','s-weather-bird-intensity','s-weather-bird-size','s-weather-bird-speed','s-weather-bird-flock','s-weather-bird-opacity','s-weather-bird-height','s-weather-bird-diversity','s-weather-bird-rare'],
  's-weather-season-owls':['s-weather-owl-intensity','s-weather-owl-size','s-weather-owl-speed','s-weather-owl-opacity','s-weather-owl-diversity'],
  's-weather-season-crystals':['s-weather-crystal-intensity','s-weather-crystal-size','s-weather-crystal-speed','s-weather-crystal-opacity'],
  's-weather-cold-frost':['s-weather-cold-frost-intensity','s-weather-cold-frost-width','s-weather-cold-frost-opacity']
};
function syncWeatherControlVisibility(){
  for(const [toggleId,ids] of Object.entries(WEATHER_DEPENDENT_CONTROLS)){const toggle=document.getElementById(toggleId),show=toggle?.checked!==false;for(const id of ids){const control=document.getElementById(id),row=control?.closest('.s-row');if(row){row.hidden=!show;row.setAttribute('aria-hidden',show?'false':'true');}}}
  const master=document.getElementById('s-weather-seasonal-effects'),enabled=master?.checked!==false;for(const section of document.querySelectorAll('.s-section[data-settings-tab="naturescape"]')){if(section.id==='settings-naturescape-overview')continue;section.classList.toggle('settings-effect-disabled',!enabled);const grid=section.querySelector('.settings-grid');if(grid)grid.hidden=!enabled;}
}

function weatherTuningFromForm(){const out={};for(const [id,key] of WEATHER_TUNING_FIELDS){const el=document.getElementById(id);out[key]=Number(el?.value??WEATHER_TUNING_DEFAULTS[key]);}for(const [id,key] of WEATHER_TUNING_CHECKS){const el=document.getElementById(id);out[key]=el?el.checked:WEATHER_TUNING_DEFAULTS[key];}return out;}
function setWeatherTuningForm(source={}){for(const [id,key] of WEATHER_TUNING_FIELDS){const el=document.getElementById(id);if(el)el.value=String(source[key]??WEATHER_TUNING_DEFAULTS[key]);}for(const [id,key] of WEATHER_TUNING_CHECKS){const el=document.getElementById(id);if(el)el.checked=source[key]!==false;}}
function updateWeatherTuningLabels(source={}){for(const [id,key] of WEATHER_TUNING_FIELDS){const el=document.getElementById(id+'-value');if(el)el.textContent=`${source[key]??WEATHER_TUNING_DEFAULTS[key]}%`;}syncWeatherControlVisibility();}
function resetWeatherTuningForm(source=WEATHER_TUNING_DEFAULTS){setWeatherTuningForm(source);updateWeatherTuningLabels(source);syncWeatherControlVisibility();}
LibreDisplayRuntime.exposeModule('appearance',{WEATHER_TUNING_DEFAULTS,WEATHER_TUNING_FIELDS,WEATHER_TUNING_CHECKS,WEATHER_TUNING_KEYS,WEATHER_DEPENDENT_CONTROLS,weatherTuningFromForm,setWeatherTuningForm,updateWeatherTuningLabels,resetWeatherTuningForm,syncWeatherControlVisibility},{},{globalFunctions:[],globalStates:[]});
