// Granular weather-effect tuning form helpers.
const WEATHER_TUNING_DEFAULTS={
  weatherRainWidth:100,weatherRainSpeed:100,weatherRainOpacity:100,weatherRainAngle:100,weatherRainDepth:100,weatherRainSplashSize:100,weatherRainGlow:100,
  weatherSnowSpeed:100,weatherSnowOpacity:100,weatherSnowSpin:100,weatherSnowDepth:100,
  weatherFogOpacity:100,weatherFogBlur:100,weatherFogLayerHeight:100,
  weatherCloudDensity:100,weatherCloudOpacity:100,weatherCloudSpeed:100,weatherCloudScale:100,weatherSunGlow:100,weatherSunRaySpeed:100,weatherLightningSize:100,weatherLightningFlash:100,weatherLightningBolts:100,
  weatherSeasonLeavesSize:100,weatherSeasonLeavesSpeed:100,weatherSeasonLeavesWind:100,weatherSeasonLeavesOpacity:100,
  weatherSeasonGrassHeight:100,weatherSeasonGrassSway:100,weatherSeasonGrassOpacity:100,
  weatherSeasonPetalSize:100,weatherSeasonPetalSpeed:100,weatherSeasonPetalOpacity:100,
  weatherSeasonBees:true,weatherSeasonBeeIntensity:55,weatherSeasonBeeSize:100,weatherSeasonBeeSpeed:100,weatherSeasonBeeOpacity:100,weatherSeasonButterflies:true,weatherSeasonButterflyIntensity:50,weatherSeasonButterflySize:100,weatherSeasonButterflySpeed:100,weatherSeasonButterflyOpacity:100,weatherSeasonFireflies:true,weatherSeasonFireflyIntensity:70,weatherSeasonFireflySize:100,weatherSeasonFireflySpeed:100,weatherSeasonFireflyGlow:100,weatherSeasonFireflyOpacity:100,
  weatherSeasonBirds:true,weatherSeasonBirdIntensity:55,weatherSeasonBirdSize:100,weatherSeasonBirdSpeed:100,weatherSeasonBirdFlock:60,weatherSeasonBirdOpacity:100,weatherSeasonBirdHeight:100,weatherSeasonCrystalIntensity:70,weatherSeasonCrystalSize:100,weatherSeasonCrystalSpeed:100,weatherSeasonCrystalOpacity:100,weatherColdFrostWidth:100,weatherColdFrostOpacity:100
};
const WEATHER_TUNING_FIELDS=[
  ['s-weather-rain-width','weatherRainWidth'],['s-weather-rain-speed','weatherRainSpeed'],['s-weather-rain-opacity','weatherRainOpacity'],['s-weather-rain-angle','weatherRainAngle'],['s-weather-rain-depth','weatherRainDepth'],['s-weather-rain-splash-size','weatherRainSplashSize'],['s-weather-rain-glow','weatherRainGlow'],
  ['s-weather-snow-speed','weatherSnowSpeed'],['s-weather-snow-opacity','weatherSnowOpacity'],['s-weather-snow-spin','weatherSnowSpin'],['s-weather-snow-depth','weatherSnowDepth'],
  ['s-weather-fog-opacity','weatherFogOpacity'],['s-weather-fog-blur','weatherFogBlur'],['s-weather-fog-layer-height','weatherFogLayerHeight'],
  ['s-weather-cloud-density','weatherCloudDensity'],['s-weather-cloud-opacity','weatherCloudOpacity'],['s-weather-cloud-speed','weatherCloudSpeed'],['s-weather-cloud-scale','weatherCloudScale'],['s-weather-sun-glow','weatherSunGlow'],['s-weather-sun-ray-speed','weatherSunRaySpeed'],['s-weather-lightning-size','weatherLightningSize'],['s-weather-lightning-flash','weatherLightningFlash'],['s-weather-lightning-bolts','weatherLightningBolts'],
  ['s-weather-leaves-size','weatherSeasonLeavesSize'],['s-weather-leaves-speed','weatherSeasonLeavesSpeed'],['s-weather-leaves-wind','weatherSeasonLeavesWind'],['s-weather-leaves-opacity','weatherSeasonLeavesOpacity'],
  ['s-weather-grass-height','weatherSeasonGrassHeight'],['s-weather-grass-sway','weatherSeasonGrassSway'],['s-weather-grass-opacity','weatherSeasonGrassOpacity'],
  ['s-weather-petal-size','weatherSeasonPetalSize'],['s-weather-petal-speed','weatherSeasonPetalSpeed'],['s-weather-petal-opacity','weatherSeasonPetalOpacity'],
  ['s-weather-bee-intensity','weatherSeasonBeeIntensity'],['s-weather-bee-size','weatherSeasonBeeSize'],['s-weather-bee-speed','weatherSeasonBeeSpeed'],['s-weather-bee-opacity','weatherSeasonBeeOpacity'],['s-weather-butterfly-intensity','weatherSeasonButterflyIntensity'],['s-weather-butterfly-size','weatherSeasonButterflySize'],['s-weather-butterfly-speed','weatherSeasonButterflySpeed'],['s-weather-butterfly-opacity','weatherSeasonButterflyOpacity'],['s-weather-firefly-intensity','weatherSeasonFireflyIntensity'],['s-weather-firefly-size','weatherSeasonFireflySize'],['s-weather-firefly-speed','weatherSeasonFireflySpeed'],['s-weather-firefly-glow','weatherSeasonFireflyGlow'],['s-weather-firefly-opacity','weatherSeasonFireflyOpacity'],['s-weather-bird-intensity','weatherSeasonBirdIntensity'],['s-weather-bird-size','weatherSeasonBirdSize'],['s-weather-bird-speed','weatherSeasonBirdSpeed'],['s-weather-bird-flock','weatherSeasonBirdFlock'],['s-weather-bird-opacity','weatherSeasonBirdOpacity'],['s-weather-bird-height','weatherSeasonBirdHeight'],['s-weather-crystal-intensity','weatherSeasonCrystalIntensity'],['s-weather-crystal-size','weatherSeasonCrystalSize'],['s-weather-crystal-speed','weatherSeasonCrystalSpeed'],['s-weather-crystal-opacity','weatherSeasonCrystalOpacity'],['s-weather-cold-frost-width','weatherColdFrostWidth'],['s-weather-cold-frost-opacity','weatherColdFrostOpacity']
];
const WEATHER_TUNING_CHECKS=[['s-weather-season-bees','weatherSeasonBees'],['s-weather-season-butterflies','weatherSeasonButterflies'],['s-weather-season-fireflies','weatherSeasonFireflies'],['s-weather-season-birds','weatherSeasonBirds']];
const WEATHER_TUNING_KEYS=[...Object.keys(WEATHER_TUNING_DEFAULTS)];
function weatherTuningFromForm(){const out={};for(const [id,key] of WEATHER_TUNING_FIELDS){const el=document.getElementById(id);out[key]=Number(el?.value??WEATHER_TUNING_DEFAULTS[key]);}for(const [id,key] of WEATHER_TUNING_CHECKS){const el=document.getElementById(id);out[key]=el?el.checked:WEATHER_TUNING_DEFAULTS[key];}return out;}
function setWeatherTuningForm(source={}){for(const [id,key] of WEATHER_TUNING_FIELDS){const el=document.getElementById(id);if(el)el.value=String(source[key]??WEATHER_TUNING_DEFAULTS[key]);}for(const [id,key] of WEATHER_TUNING_CHECKS){const el=document.getElementById(id);if(el)el.checked=source[key]!==false;}}
function updateWeatherTuningLabels(source={}){for(const [id,key] of WEATHER_TUNING_FIELDS){const el=document.getElementById(id+'-value');if(el)el.textContent=`${source[key]??WEATHER_TUNING_DEFAULTS[key]}%`;}}
function resetWeatherTuningForm(source=WEATHER_TUNING_DEFAULTS){setWeatherTuningForm(source);updateWeatherTuningLabels(source);}
LibreDisplayRuntime.exposeModule('appearance',{WEATHER_TUNING_DEFAULTS,WEATHER_TUNING_FIELDS,WEATHER_TUNING_CHECKS,WEATHER_TUNING_KEYS,weatherTuningFromForm,setWeatherTuningForm,updateWeatherTuningLabels,resetWeatherTuningForm},{},{globalFunctions:[],globalStates:[]});
