(function(){
  const esc=value=>String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
  const safeUrl=value=>/^https?:\/\//i.test(String(value||''))?String(value):'';
  const weatherSong=()=>{try{const code=Number(LibreDisplayRuntime.getModule('config')?.wxData?.current?.weather_code);if([51,53,55,61,63,65,80,81,82].includes(code))return 'Looks Like Rain';if([71,73,75,77,85,86].includes(code))return 'Cold Rain and Snow';if([95,96,99].includes(code))return 'The Wheel';if([0].includes(code))return 'Here Comes Sunshine';if([45,48].includes(code))return 'Box of Rain';return 'Eyes of the World';}catch{return 'Eyes of the World';}};
  let activeMode='off';const applyMode=mode=>{activeMode=['subtle','psychedelic'].includes(mode)?mode:'off';document.body.classList.toggle('ld-deadhead-subtle',activeMode==='subtle');document.body.classList.toggle('ld-deadhead-psychedelic',activeMode==='psychedelic');};const syncMode=()=>{if(!document.querySelector('.deadhead-panel'))applyMode('off');};new MutationObserver(()=>queueMicrotask(syncMode)).observe(document.body,{childList:true,subtree:true});
  const renderShow=(show,index,total)=>{if(!show)return '<div class="deadhead-empty">No historical show was found for this date and era.</div>';const where=[show.venue,show.location].filter(Boolean).join(' · ');return `<div class="deadhead-show" data-show-index="${index}"><div class="deadhead-show-kicker">Show ${index+1} of ${total}</div><div class="deadhead-show-date">${esc(show.date)}</div><div class="deadhead-show-venue">${esc(where)}</div><div class="deadhead-show-actions"><a href="${esc(safeUrl(show.relistenUrl))}" target="_blank" rel="noopener">Listen on Relisten</a><a href="${esc(safeUrl(show.archiveUrl))}" target="_blank" rel="noopener">Internet Archive</a></div></div>`;};
  const renderSetlist=data=>{const row=data?.setlist;if(!row?.sets?.length)return '';const sets=row.sets.map(group=>`<div class="deadhead-set"><b>${esc(group.name||'Set')}</b><span>${group.songs.map(esc).join(' · ')}</span></div>`).join(''),hits=(row.favoriteSongHits||[]).map(x=>`<span class="deadhead-favorite-song">${esc(x)}</span>`).join(''),url=safeUrl(row.url);return `<div class="deadhead-setlist"><div class="deadhead-mini-title">Setlist${url?` · <a href="${esc(url)}" target="_blank" rel="noopener">Source: setlist.fm</a>`:''}</div>${sets}${hits?`<div class="deadhead-favorites">Favorites in this show: ${hits}</div>`:''}</div>`;};
  const renderQuote=quote=>quote?`<figure class="deadhead-quote"><blockquote>“${esc(quote.quote)}”</blockquote><figcaption>— ${esc(quote.member)}${safeUrl(quote.url)?` · <a href="${esc(safeUrl(quote.url))}" target="_blank" rel="noopener">${esc(quote.source||'Source')}</a>`:''}</figcaption></figure>`:'';
  window.LibreDisplayIntegrationRenderers=window.LibreDisplayIntegrationRenderers||{};
  window.LibreDisplayIntegrationRenderers['grateful-dead']=(target,data)=>{if(!target)return;applyMode(data?.visualMode||'subtle');const shows=Array.isArray(data?.shows)?data.shows:[],initial=Math.max(0,Math.min(shows.length-1,Number(data?.featuredIndex)||0));let current=initial;const draw=()=>{const show=shows[current];target.innerHTML=`<div class="deadhead-panel"><div class="deadhead-orbit deadhead-orbit-a"></div><div class="deadhead-orbit deadhead-orbit-b"></div><header><span class="deadhead-mark">✺</span><div><b>Today in Dead History</b><small>${esc(data?.monthDay||data?.date||'')} · unofficial fan integration</small></div></header>${renderShow(show,current,shows.length)}<div class="deadhead-listen-prompt">Weather pick · <b>${esc(weatherSong())}</b></div>${current===initial?renderSetlist(data):''}${renderQuote(data?.quote)}<footer><button class="deadhead-another" type="button" ${shows.length<2?'disabled':''}>What should I listen to?</button><span>${shows.length} historical show${shows.length===1?'':'s'} found</span></footer></div>`;target.querySelector('.deadhead-another')?.addEventListener('click',()=>{current=shows.length?((current+1)%shows.length):0;draw();});};draw();};
})();
