(function(){
  const esc=value=>String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
  const safeUrl=value=>/^https?:\/\//i.test(String(value||''))?String(value):'';
  const states=new WeakMap();
  const weatherSong=()=>{try{const code=Number(LibreDisplayRuntime.getModule('config')?.wxData?.current?.weather_code);if([51,53,55,61,63,65,80,81,82].includes(code))return 'Looks Like Rain';if([71,73,75,77,85,86].includes(code))return 'Cold Rain and Snow';if([95,96,99].includes(code))return 'The Wheel';if([0].includes(code))return 'Here Comes Sunshine';if([45,48].includes(code))return 'Box of Rain';return 'Eyes of the World';}catch{return 'Eyes of the World';}};
  let activeMode='off';
  const applyMode=mode=>{activeMode=['subtle','psychedelic'].includes(mode)?mode:'off';document.body.classList.toggle('ld-deadhead-subtle',activeMode==='subtle');document.body.classList.toggle('ld-deadhead-psychedelic',activeMode==='psychedelic');};
  const syncMode=()=>{if(!document.querySelector('.deadhead-panel'))applyMode('off');};
  new MutationObserver(()=>queueMicrotask(syncMode)).observe(document.body,{childList:true,subtree:true});

  const showWhere=show=>[show?.venue,show?.location].filter(Boolean).join(' · ');
  const sourceLink=(url,label)=>safeUrl(url)?`<a href="${esc(url)}" target="_blank" rel="noopener">${esc(label)}</a>`:'';
  const renderShow=(show,index,total)=>{if(!show)return '<div class="deadhead-empty">No historical show was found for this date and era.</div>';return `<section class="deadhead-show" data-show-index="${index}"><div class="deadhead-show-topline"><span class="deadhead-show-kicker">Show ${index+1} of ${total}</span><span class="deadhead-recordings">${Number(show.recordings)||0} recording${Number(show.recordings)===1?'':'s'}</span></div><div class="deadhead-show-date">${esc(show.date)}</div><div class="deadhead-show-venue">${esc(showWhere(show))}</div><div class="deadhead-show-actions">${sourceLink(show.relistenUrl,'Listen on Relisten')}${sourceLink(show.archiveUrl,'Internet Archive')}${sourceLink(show.jerrybaseUrl,'JerryBase')}</div></section>`;};
  const renderSetlist=(data,show)=>{if(data?.setlistsEnabled===false)return '';const row=data?.setlists?.[show?.date]||null;if(!row?.sets?.length){const url=safeUrl(show?.jerrybaseUrl);return `<section class="deadhead-setlist deadhead-setlist-missing"><div class="deadhead-mini-title">Setlist</div><div class="deadhead-setlist-note">Not preloaded for this show${url?` · <a href="${esc(url)}" target="_blank" rel="noopener">Open JerryBase</a>`:''}</div></section>`;}const sets=row.sets.map(group=>`<div class="deadhead-set"><b>${esc(group.name||'Set')}</b><span>${(group.songs||[]).map(esc).join(' · ')}</span></div>`).join(''),hits=(row.favoriteSongHits||[]).map(x=>`<span class="deadhead-favorite-song">${esc(x)}</span>`).join(''),url=safeUrl(row.url);return `<section class="deadhead-setlist"><div class="deadhead-mini-title">Setlist · ${esc(row.attribution||'source')}${url?` · <a href="${esc(url)}" target="_blank" rel="noopener">open source</a>`:''}</div>${sets}${hits?`<div class="deadhead-favorites">Favorites in this show: ${hits}</div>`:''}</section>`;};
  const renderQuote=quote=>quote?`<figure class="deadhead-quote"><blockquote>“${esc(quote.quote)}”</blockquote><figcaption>— ${esc(quote.member)}${safeUrl(quote.url)?` · <a href="${esc(safeUrl(quote.url))}" target="_blank" rel="noopener">${esc(quote.source||'Source')}</a>`:''}</figcaption></figure>`:'';
  const yearStrip=(shows,current)=>`<div class="deadhead-year-strip" role="list" aria-label="Shows played on this date">${shows.map((show,i)=>`<button type="button" class="deadhead-year${i===current?' active':''}" data-dead-show="${i}" title="${esc(showWhere(show))}">${esc(show.year||show.date?.slice(0,4)||'?')}</button>`).join('')}</div>`;
  const compactList=(shows,current)=>`<div class="deadhead-show-list" role="list">${shows.map((show,i)=>`<button type="button" class="deadhead-show-row${i===current?' active':''}" data-dead-show="${i}"><b>${esc(show.year||'')}</b><span>${esc(show.venue||'Unknown venue')}</span><small>${esc(show.location||'')}</small></button>`).join('')}</div>`;
  const renderBrowser=(data,shows,current)=>data?.showBrowser==='minimal'?'':data?.showBrowser==='list'?compactList(shows,current):yearStrip(shows,current);
  const nextIndex=(current,total,delta=1)=>total?((current+delta+total)%total):0;
  const deterministicJump=(current,total,seed)=>{if(total<2)return current;let value=0;for(const ch of String(seed||''))value=(value*33+ch.charCodeAt(0))>>>0;const step=1+(value%(total-1));return (current+step)%total;};

  window.LibreDisplayIntegrationRenderers=window.LibreDisplayIntegrationRenderers||{};
  window.LibreDisplayIntegrationRenderers['grateful-dead']=(target,data)=>{
    if(!target)return;
    const previous=states.get(target);if(previous?.showTimer)clearInterval(previous.showTimer);if(previous?.quoteTimer)clearInterval(previous.quoteTimer);
    applyMode(data?.visualMode||'subtle');
    const shows=Array.isArray(data?.shows)?data.shows:[],quotes=Array.isArray(data?.quotes)&&data.quotes.length?data.quotes:(data?.quote?[data.quote]:[]),initial=Math.max(0,Math.min(Math.max(0,shows.length-1),Number(data?.featuredIndex)||0));
    const state={current:initial,quoteIndex:0,showTimer:0,quoteTimer:0,paused:false};states.set(target,state);
    const draw=()=>{const show=shows[state.current],quote=quotes[state.quoteIndex%Math.max(1,quotes.length)];target.innerHTML=`<div class="deadhead-panel"><div class="deadhead-orbit deadhead-orbit-a"></div><div class="deadhead-orbit deadhead-orbit-b"></div><header><span class="deadhead-mark">✺</span><div><b>Today in Dead History</b><small>${esc(data?.monthDay||data?.date||'')} · ${shows.length} show${shows.length===1?'':'s'} in rotation · unofficial fan integration</small></div></header>${renderBrowser(data,shows,state.current)}<div class="deadhead-nav"><button type="button" class="deadhead-prev" ${shows.length<2?'disabled':''} aria-label="Previous historical show">‹</button><span>${shows.length?`${state.current+1} / ${shows.length}`:'0 / 0'}</span><button type="button" class="deadhead-next" ${shows.length<2?'disabled':''} aria-label="Next historical show">›</button></div>${renderShow(show,state.current,shows.length)}<div class="deadhead-listen-prompt">Weather pick · <b>${esc(weatherSong())}</b></div>${renderSetlist(data,show)}${renderQuote(quote)}<footer><button class="deadhead-another" type="button" ${shows.length<2?'disabled':''}>What should I listen to?</button><div class="deadhead-footer-meta"><span>${data?.autoRotate?'Auto-rotating':'Manual browsing'}</span><span>${Object.keys(data?.setlists||{}).length} setlist${Object.keys(data?.setlists||{}).length===1?'':'s'} loaded</span></div></footer></div>`;
      target.querySelectorAll('[data-dead-show]').forEach(btn=>btn.addEventListener('click',()=>{state.current=Math.max(0,Math.min(shows.length-1,Number(btn.dataset.deadShow)||0));draw();}));
      target.querySelector('.deadhead-prev')?.addEventListener('click',()=>{state.current=nextIndex(state.current,shows.length,-1);draw();});
      target.querySelector('.deadhead-next')?.addEventListener('click',()=>{state.current=nextIndex(state.current,shows.length,1);draw();});
      target.querySelector('.deadhead-another')?.addEventListener('click',()=>{state.current=deterministicJump(state.current,shows.length,`${Date.now()}-${state.current}`);draw();});
    };
    draw();
    target.addEventListener('mouseenter',()=>{state.paused=true;},{passive:true});target.addEventListener('mouseleave',()=>{state.paused=false;},{passive:true});
    if(data?.autoRotate!==false&&shows.length>1){const ms=Math.max(15,Number(data?.rotationSeconds)||30)*1000;state.showTimer=setInterval(()=>{if(state.paused||!target.isConnected)return;state.current=nextIndex(state.current,shows.length,1);draw();},ms);}
    if(data?.quoteRotate!==false&&quotes.length>1){const ms=Math.max(30,Number(data?.quoteSeconds)||60)*1000;state.quoteTimer=setInterval(()=>{if(state.paused||!target.isConnected)return;state.quoteIndex=(state.quoteIndex+1)%quotes.length;draw();},ms);}
  };
})();
